// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: chat/chat.proto

package chat

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 会话类型
type ConversationType int32

const (
	ConversationType_CONVERSATION_TYPE_UNSPECIFIED ConversationType = 0
	ConversationType_CONVERSATION_TYPE_PRIVATE     ConversationType = 1 // 单聊
	ConversationType_CONVERSATION_TYPE_GROUP       ConversationType = 2 // 群聊
)

// Enum value maps for ConversationType.
var (
	ConversationType_name = map[int32]string{
		0: "CONVERSATION_TYPE_UNSPECIFIED",
		1: "CONVERSATION_TYPE_PRIVATE",
		2: "CONVERSATION_TYPE_GROUP",
	}
	ConversationType_value = map[string]int32{
		"CONVERSATION_TYPE_UNSPECIFIED": 0,
		"CONVERSATION_TYPE_PRIVATE":     1,
		"CONVERSATION_TYPE_GROUP":       2,
	}
)

func (x ConversationType) Enum() *ConversationType {
	p := new(ConversationType)
	*p = x
	return p
}

func (x ConversationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConversationType) Descriptor() protoreflect.EnumDescriptor {
	return file_chat_chat_proto_enumTypes[0].Descriptor()
}

func (ConversationType) Type() protoreflect.EnumType {
	return &file_chat_chat_proto_enumTypes[0]
}

func (x ConversationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConversationType.Descriptor instead.
func (ConversationType) EnumDescriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{0}
}

// 消息类型
type MessageType int32

const (
	MessageType_MESSAGE_TYPE_UNSPECIFIED MessageType = 0
	MessageType_MESSAGE_TYPE_TEXT        MessageType = 1
	MessageType_MESSAGE_TYPE_IMAGE       MessageType = 2
	MessageType_MESSAGE_TYPE_SYSTEM      MessageType = 3
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "MESSAGE_TYPE_UNSPECIFIED",
		1: "MESSAGE_TYPE_TEXT",
		2: "MESSAGE_TYPE_IMAGE",
		3: "MESSAGE_TYPE_SYSTEM",
	}
	MessageType_value = map[string]int32{
		"MESSAGE_TYPE_UNSPECIFIED": 0,
		"MESSAGE_TYPE_TEXT":        1,
		"MESSAGE_TYPE_IMAGE":       2,
		"MESSAGE_TYPE_SYSTEM":      3,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_chat_chat_proto_enumTypes[1].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_chat_chat_proto_enumTypes[1]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{1}
}

// 基础会话结构
type Conversation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          ConversationType       `protobuf:"varint,2,opt,name=type,proto3,enum=social.chat.ConversationType" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`     // 群聊名称，单聊时可为空或对方昵称
	Avatar        string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"` // 群聊头像，单聊时可为空或对方头像
	LastMessage   *Message               `protobuf:"bytes,5,opt,name=last_message,json=lastMessage,proto3" json:"last_message,omitempty"`
	UnreadCount   uint32                 `protobuf:"varint,6,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // 排序用，通常是 last_message.created_at
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Conversation) Reset() {
	*x = Conversation{}
	mi := &file_chat_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Conversation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Conversation) ProtoMessage() {}

func (x *Conversation) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Conversation.ProtoReflect.Descriptor instead.
func (*Conversation) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{0}
}

func (x *Conversation) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Conversation) GetType() ConversationType {
	if x != nil {
		return x.Type
	}
	return ConversationType_CONVERSATION_TYPE_UNSPECIFIED
}

func (x *Conversation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Conversation) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *Conversation) GetLastMessage() *Message {
	if x != nil {
		return x.LastMessage
	}
	return nil
}

func (x *Conversation) GetUnreadCount() uint32 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

func (x *Conversation) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type SenderInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SenderInfo) Reset() {
	*x = SenderInfo{}
	mi := &file_chat_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SenderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SenderInfo) ProtoMessage() {}

func (x *SenderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SenderInfo.ProtoReflect.Descriptor instead.
func (*SenderInfo) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{1}
}

func (x *SenderInfo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SenderInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SenderInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *SenderInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

// 基础消息结构
type Message struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	LocalId        uint64                 `protobuf:"varint,7,opt,name=local_id,json=localId,proto3" json:"local_id,omitempty"` // 会话内唯一ID
	ConversationId uint64                 `protobuf:"varint,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	SenderId       uint64                 `protobuf:"varint,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Content        string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Type           MessageType            `protobuf:"varint,5,opt,name=type,proto3,enum=social.chat.MessageType" json:"type,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Sender         *SenderInfo            `protobuf:"bytes,8,opt,name=sender,proto3" json:"sender,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_chat_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{2}
}

func (x *Message) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Message) GetLocalId() uint64 {
	if x != nil {
		return x.LocalId
	}
	return 0
}

func (x *Message) GetConversationId() uint64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

func (x *Message) GetSenderId() uint64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MESSAGE_TYPE_UNSPECIFIED
}

func (x *Message) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Message) GetSender() *SenderInfo {
	if x != nil {
		return x.Sender
	}
	return nil
}

// 1. 发送消息
type SendMessageRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId uint64                 `protobuf:"varint,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"` // 发送到哪个会话
	Content        string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Type           MessageType            `protobuf:"varint,3,opt,name=type,proto3,enum=social.chat.MessageType" json:"type,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_chat_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{3}
}

func (x *SendMessageRequest) GetConversationId() uint64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

func (x *SendMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendMessageRequest) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MESSAGE_TYPE_UNSPECIFIED
}

type SendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` // 返回发送成功的完整消息对象（含ID和时间）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_chat_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{4}
}

func (x *SendMessageResponse) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

// 2. 获取会话列表 (支持分页)
type GetConversationListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      uint32                 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`   // 每页数量，默认 20
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"` // 分页游标，第一页传空
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConversationListRequest) Reset() {
	*x = GetConversationListRequest{}
	mi := &file_chat_chat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConversationListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConversationListRequest) ProtoMessage() {}

func (x *GetConversationListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConversationListRequest.ProtoReflect.Descriptor instead.
func (*GetConversationListRequest) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{5}
}

func (x *GetConversationListRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetConversationListRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type GetConversationListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conversations []*Conversation        `protobuf:"bytes,1,rep,name=conversations,proto3" json:"conversations,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"` // 下一页游标，为空表示无更多数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConversationListResponse) Reset() {
	*x = GetConversationListResponse{}
	mi := &file_chat_chat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConversationListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConversationListResponse) ProtoMessage() {}

func (x *GetConversationListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConversationListResponse.ProtoReflect.Descriptor instead.
func (*GetConversationListResponse) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{6}
}

func (x *GetConversationListResponse) GetConversations() []*Conversation {
	if x != nil {
		return x.Conversations
	}
	return nil
}

func (x *GetConversationListResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// 3. 获取消息列表 (支持分页)
type GetMessageListRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId uint64                 `protobuf:"varint,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	PageSize       uint32                 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`   // 每页数量，默认 50
	PageToken      string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"` // 分页游标，第一页传空
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetMessageListRequest) Reset() {
	*x = GetMessageListRequest{}
	mi := &file_chat_chat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageListRequest) ProtoMessage() {}

func (x *GetMessageListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageListRequest.ProtoReflect.Descriptor instead.
func (*GetMessageListRequest) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{7}
}

func (x *GetMessageListRequest) GetConversationId() uint64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

func (x *GetMessageListRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetMessageListRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type GetMessageListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"` // 下一页游标
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessageListResponse) Reset() {
	*x = GetMessageListResponse{}
	mi := &file_chat_chat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageListResponse) ProtoMessage() {}

func (x *GetMessageListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageListResponse.ProtoReflect.Descriptor instead.
func (*GetMessageListResponse) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{8}
}

func (x *GetMessageListResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *GetMessageListResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// 4. 标记已读
type MarkAsReadRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId uint64                 `protobuf:"varint,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	MessageIds     []uint64               `protobuf:"varint,2,rep,packed,name=message_ids,json=messageIds,proto3" json:"message_ids,omitempty"` // 要标记为已读的消息ID列表 (通常是最新的一条，表示之前的都已读，或者是具体的ID列表)
	// 简化起见，通常传最后一条读取的消息ID，服务端将 <= 该ID的消息标记为已读
	// 这里我们采用：传入最后一条阅读的消息ID
	LastReadMessageId uint64 `protobuf:"varint,3,opt,name=last_read_message_id,json=lastReadMessageId,proto3" json:"last_read_message_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MarkAsReadRequest) Reset() {
	*x = MarkAsReadRequest{}
	mi := &file_chat_chat_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAsReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAsReadRequest) ProtoMessage() {}

func (x *MarkAsReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAsReadRequest.ProtoReflect.Descriptor instead.
func (*MarkAsReadRequest) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{9}
}

func (x *MarkAsReadRequest) GetConversationId() uint64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

func (x *MarkAsReadRequest) GetMessageIds() []uint64 {
	if x != nil {
		return x.MessageIds
	}
	return nil
}

func (x *MarkAsReadRequest) GetLastReadMessageId() uint64 {
	if x != nil {
		return x.LastReadMessageId
	}
	return 0
}

type MarkAsReadResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId uint64                 `protobuf:"varint,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	UnreadCount    uint32                 `protobuf:"varint,2,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MarkAsReadResponse) Reset() {
	*x = MarkAsReadResponse{}
	mi := &file_chat_chat_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAsReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAsReadResponse) ProtoMessage() {}

func (x *MarkAsReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAsReadResponse.ProtoReflect.Descriptor instead.
func (*MarkAsReadResponse) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{10}
}

func (x *MarkAsReadResponse) GetConversationId() uint64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

func (x *MarkAsReadResponse) GetUnreadCount() uint32 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

// 5. 创建会话 (单聊或群聊)
type CreateConversationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Type           ConversationType       `protobuf:"varint,1,opt,name=type,proto3,enum=social.chat.ConversationType" json:"type,omitempty"`
	ParticipantIds []uint64               `protobuf:"varint,2,rep,packed,name=participant_ids,json=participantIds,proto3" json:"participant_ids,omitempty"` // 成员ID列表 (不包含自己，或者包含也可以，后端处理)
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                                                   // 群聊名称 (仅群聊有效)
	Avatar         string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`                                               // 群聊头像 (仅群聊有效)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateConversationRequest) Reset() {
	*x = CreateConversationRequest{}
	mi := &file_chat_chat_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateConversationRequest) ProtoMessage() {}

func (x *CreateConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateConversationRequest.ProtoReflect.Descriptor instead.
func (*CreateConversationRequest) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{11}
}

func (x *CreateConversationRequest) GetType() ConversationType {
	if x != nil {
		return x.Type
	}
	return ConversationType_CONVERSATION_TYPE_UNSPECIFIED
}

func (x *CreateConversationRequest) GetParticipantIds() []uint64 {
	if x != nil {
		return x.ParticipantIds
	}
	return nil
}

func (x *CreateConversationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateConversationRequest) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type CreateConversationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conversation  *Conversation          `protobuf:"bytes,1,opt,name=conversation,proto3" json:"conversation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateConversationResponse) Reset() {
	*x = CreateConversationResponse{}
	mi := &file_chat_chat_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateConversationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateConversationResponse) ProtoMessage() {}

func (x *CreateConversationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateConversationResponse.ProtoReflect.Descriptor instead.
func (*CreateConversationResponse) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{12}
}

func (x *CreateConversationResponse) GetConversation() *Conversation {
	if x != nil {
		return x.Conversation
	}
	return nil
}

// 6. 消息推送 (服务端 -> 客户端)
type MessagePush struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessagePush) Reset() {
	*x = MessagePush{}
	mi := &file_chat_chat_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessagePush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessagePush) ProtoMessage() {}

func (x *MessagePush) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessagePush.ProtoReflect.Descriptor instead.
func (*MessagePush) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{13}
}

func (x *MessagePush) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type ConversationPush struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conversation  *Conversation          `protobuf:"bytes,1,opt,name=conversation,proto3" json:"conversation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConversationPush) Reset() {
	*x = ConversationPush{}
	mi := &file_chat_chat_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationPush) ProtoMessage() {}

func (x *ConversationPush) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationPush.ProtoReflect.Descriptor instead.
func (*ConversationPush) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{14}
}

func (x *ConversationPush) GetConversation() *Conversation {
	if x != nil {
		return x.Conversation
	}
	return nil
}

// ----------------------
// 统一载荷
// ----------------------
type ChatPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ChatPayload_SendMessage
	//	*ChatPayload_SendMessageResponse
	//	*ChatPayload_GetConversationList
	//	*ChatPayload_GetConversationListResponse
	//	*ChatPayload_GetMessageList
	//	*ChatPayload_GetMessageListResponse
	//	*ChatPayload_MarkAsRead
	//	*ChatPayload_MarkAsReadResponse
	//	*ChatPayload_CreateConversation
	//	*ChatPayload_CreateConversationResponse
	//	*ChatPayload_MessagePush
	//	*ChatPayload_ConversationPush
	Payload       isChatPayload_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatPayload) Reset() {
	*x = ChatPayload{}
	mi := &file_chat_chat_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatPayload) ProtoMessage() {}

func (x *ChatPayload) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatPayload.ProtoReflect.Descriptor instead.
func (*ChatPayload) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{15}
}

func (x *ChatPayload) GetPayload() isChatPayload_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ChatPayload) GetSendMessage() *SendMessageRequest {
	if x != nil {
		if x, ok := x.Payload.(*ChatPayload_SendMessage); ok {
			return x.SendMessage
		}
	}
	return nil
}

func (x *ChatPayload) GetSendMessageResponse() *SendMessageResponse {
	if x != nil {
		if x, ok := x.Payload.(*ChatPayload_SendMessageResponse); ok {
			return x.SendMessageResponse
		}
	}
	return nil
}

func (x *ChatPayload) GetGetConversationList() *GetConversationListRequest {
	if x != nil {
		if x, ok := x.Payload.(*ChatPayload_GetConversationList); ok {
			return x.GetConversationList
		}
	}
	return nil
}

func (x *ChatPayload) GetGetConversationListResponse() *GetConversationListResponse {
	if x != nil {
		if x, ok := x.Payload.(*ChatPayload_GetConversationListResponse); ok {
			return x.GetConversationListResponse
		}
	}
	return nil
}

func (x *ChatPayload) GetGetMessageList() *GetMessageListRequest {
	if x != nil {
		if x, ok := x.Payload.(*ChatPayload_GetMessageList); ok {
			return x.GetMessageList
		}
	}
	return nil
}

func (x *ChatPayload) GetGetMessageListResponse() *GetMessageListResponse {
	if x != nil {
		if x, ok := x.Payload.(*ChatPayload_GetMessageListResponse); ok {
			return x.GetMessageListResponse
		}
	}
	return nil
}

func (x *ChatPayload) GetMarkAsRead() *MarkAsReadRequest {
	if x != nil {
		if x, ok := x.Payload.(*ChatPayload_MarkAsRead); ok {
			return x.MarkAsRead
		}
	}
	return nil
}

func (x *ChatPayload) GetMarkAsReadResponse() *MarkAsReadResponse {
	if x != nil {
		if x, ok := x.Payload.(*ChatPayload_MarkAsReadResponse); ok {
			return x.MarkAsReadResponse
		}
	}
	return nil
}

func (x *ChatPayload) GetCreateConversation() *CreateConversationRequest {
	if x != nil {
		if x, ok := x.Payload.(*ChatPayload_CreateConversation); ok {
			return x.CreateConversation
		}
	}
	return nil
}

func (x *ChatPayload) GetCreateConversationResponse() *CreateConversationResponse {
	if x != nil {
		if x, ok := x.Payload.(*ChatPayload_CreateConversationResponse); ok {
			return x.CreateConversationResponse
		}
	}
	return nil
}

func (x *ChatPayload) GetMessagePush() *MessagePush {
	if x != nil {
		if x, ok := x.Payload.(*ChatPayload_MessagePush); ok {
			return x.MessagePush
		}
	}
	return nil
}

func (x *ChatPayload) GetConversationPush() *ConversationPush {
	if x != nil {
		if x, ok := x.Payload.(*ChatPayload_ConversationPush); ok {
			return x.ConversationPush
		}
	}
	return nil
}

type isChatPayload_Payload interface {
	isChatPayload_Payload()
}

type ChatPayload_SendMessage struct {
	SendMessage *SendMessageRequest `protobuf:"bytes,1,opt,name=send_message,json=sendMessage,proto3,oneof"`
}

type ChatPayload_SendMessageResponse struct {
	SendMessageResponse *SendMessageResponse `protobuf:"bytes,2,opt,name=send_message_response,json=sendMessageResponse,proto3,oneof"`
}

type ChatPayload_GetConversationList struct {
	GetConversationList *GetConversationListRequest `protobuf:"bytes,3,opt,name=get_conversation_list,json=getConversationList,proto3,oneof"`
}

type ChatPayload_GetConversationListResponse struct {
	GetConversationListResponse *GetConversationListResponse `protobuf:"bytes,4,opt,name=get_conversation_list_response,json=getConversationListResponse,proto3,oneof"`
}

type ChatPayload_GetMessageList struct {
	GetMessageList *GetMessageListRequest `protobuf:"bytes,5,opt,name=get_message_list,json=getMessageList,proto3,oneof"`
}

type ChatPayload_GetMessageListResponse struct {
	GetMessageListResponse *GetMessageListResponse `protobuf:"bytes,6,opt,name=get_message_list_response,json=getMessageListResponse,proto3,oneof"`
}

type ChatPayload_MarkAsRead struct {
	MarkAsRead *MarkAsReadRequest `protobuf:"bytes,7,opt,name=mark_as_read,json=markAsRead,proto3,oneof"`
}

type ChatPayload_MarkAsReadResponse struct {
	MarkAsReadResponse *MarkAsReadResponse `protobuf:"bytes,8,opt,name=mark_as_read_response,json=markAsReadResponse,proto3,oneof"`
}

type ChatPayload_CreateConversation struct {
	CreateConversation *CreateConversationRequest `protobuf:"bytes,9,opt,name=create_conversation,json=createConversation,proto3,oneof"`
}

type ChatPayload_CreateConversationResponse struct {
	CreateConversationResponse *CreateConversationResponse `protobuf:"bytes,10,opt,name=create_conversation_response,json=createConversationResponse,proto3,oneof"`
}

type ChatPayload_MessagePush struct {
	MessagePush *MessagePush `protobuf:"bytes,11,opt,name=message_push,json=messagePush,proto3,oneof"` // 新消息推送
}

type ChatPayload_ConversationPush struct {
	ConversationPush *ConversationPush `protobuf:"bytes,12,opt,name=conversation_push,json=conversationPush,proto3,oneof"` // 新会话推送
}

func (*ChatPayload_SendMessage) isChatPayload_Payload() {}

func (*ChatPayload_SendMessageResponse) isChatPayload_Payload() {}

func (*ChatPayload_GetConversationList) isChatPayload_Payload() {}

func (*ChatPayload_GetConversationListResponse) isChatPayload_Payload() {}

func (*ChatPayload_GetMessageList) isChatPayload_Payload() {}

func (*ChatPayload_GetMessageListResponse) isChatPayload_Payload() {}

func (*ChatPayload_MarkAsRead) isChatPayload_Payload() {}

func (*ChatPayload_MarkAsReadResponse) isChatPayload_Payload() {}

func (*ChatPayload_CreateConversation) isChatPayload_Payload() {}

func (*ChatPayload_CreateConversationResponse) isChatPayload_Payload() {}

func (*ChatPayload_MessagePush) isChatPayload_Payload() {}

func (*ChatPayload_ConversationPush) isChatPayload_Payload() {}

var File_chat_chat_proto protoreflect.FileDescriptor

const file_chat_chat_proto_rawDesc = "" +
	"\n" +
	"\x0fchat/chat.proto\x12\vsocial.chat\x1a\x1fgoogle/protobuf/timestamp.proto\"\x94\x02\n" +
	"\fConversation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x121\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1d.social.chat.ConversationTypeR\x04type\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\x127\n" +
	"\flast_message\x18\x05 \x01(\v2\x14.social.chat.MessageR\vlastMessage\x12!\n" +
	"\funread_count\x18\x06 \x01(\rR\vunreadCount\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"l\n" +
	"\n" +
	"SenderInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\"\xae\x02\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x19\n" +
	"\blocal_id\x18\a \x01(\x04R\alocalId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\x04R\x0econversationId\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\x04R\bsenderId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12,\n" +
	"\x04type\x18\x05 \x01(\x0e2\x18.social.chat.MessageTypeR\x04type\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12/\n" +
	"\x06sender\x18\b \x01(\v2\x17.social.chat.SenderInfoR\x06sender\"\x85\x01\n" +
	"\x12SendMessageRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\x04R\x0econversationId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12,\n" +
	"\x04type\x18\x03 \x01(\x0e2\x18.social.chat.MessageTypeR\x04type\"E\n" +
	"\x13SendMessageResponse\x12.\n" +
	"\amessage\x18\x01 \x01(\v2\x14.social.chat.MessageR\amessage\"X\n" +
	"\x1aGetConversationListRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\rR\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"\x86\x01\n" +
	"\x1bGetConversationListResponse\x12?\n" +
	"\rconversations\x18\x01 \x03(\v2\x19.social.chat.ConversationR\rconversations\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"|\n" +
	"\x15GetMessageListRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\x04R\x0econversationId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\rR\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"r\n" +
	"\x16GetMessageListResponse\x120\n" +
	"\bmessages\x18\x01 \x03(\v2\x14.social.chat.MessageR\bmessages\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\x8e\x01\n" +
	"\x11MarkAsReadRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\x04R\x0econversationId\x12\x1f\n" +
	"\vmessage_ids\x18\x02 \x03(\x04R\n" +
	"messageIds\x12/\n" +
	"\x14last_read_message_id\x18\x03 \x01(\x04R\x11lastReadMessageId\"`\n" +
	"\x12MarkAsReadResponse\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\x04R\x0econversationId\x12!\n" +
	"\funread_count\x18\x02 \x01(\rR\vunreadCount\"\xa3\x01\n" +
	"\x19CreateConversationRequest\x121\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1d.social.chat.ConversationTypeR\x04type\x12'\n" +
	"\x0fparticipant_ids\x18\x02 \x03(\x04R\x0eparticipantIds\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\"[\n" +
	"\x1aCreateConversationResponse\x12=\n" +
	"\fconversation\x18\x01 \x01(\v2\x19.social.chat.ConversationR\fconversation\"=\n" +
	"\vMessagePush\x12.\n" +
	"\amessage\x18\x01 \x01(\v2\x14.social.chat.MessageR\amessage\"Q\n" +
	"\x10ConversationPush\x12=\n" +
	"\fconversation\x18\x01 \x01(\v2\x19.social.chat.ConversationR\fconversation\"\xa7\b\n" +
	"\vChatPayload\x12D\n" +
	"\fsend_message\x18\x01 \x01(\v2\x1f.social.chat.SendMessageRequestH\x00R\vsendMessage\x12V\n" +
	"\x15send_message_response\x18\x02 \x01(\v2 .social.chat.SendMessageResponseH\x00R\x13sendMessageResponse\x12]\n" +
	"\x15get_conversation_list\x18\x03 \x01(\v2'.social.chat.GetConversationListRequestH\x00R\x13getConversationList\x12o\n" +
	"\x1eget_conversation_list_response\x18\x04 \x01(\v2(.social.chat.GetConversationListResponseH\x00R\x1bgetConversationListResponse\x12N\n" +
	"\x10get_message_list\x18\x05 \x01(\v2\".social.chat.GetMessageListRequestH\x00R\x0egetMessageList\x12`\n" +
	"\x19get_message_list_response\x18\x06 \x01(\v2#.social.chat.GetMessageListResponseH\x00R\x16getMessageListResponse\x12B\n" +
	"\fmark_as_read\x18\a \x01(\v2\x1e.social.chat.MarkAsReadRequestH\x00R\n" +
	"markAsRead\x12T\n" +
	"\x15mark_as_read_response\x18\b \x01(\v2\x1f.social.chat.MarkAsReadResponseH\x00R\x12markAsReadResponse\x12Y\n" +
	"\x13create_conversation\x18\t \x01(\v2&.social.chat.CreateConversationRequestH\x00R\x12createConversation\x12k\n" +
	"\x1ccreate_conversation_response\x18\n" +
	" \x01(\v2'.social.chat.CreateConversationResponseH\x00R\x1acreateConversationResponse\x12=\n" +
	"\fmessage_push\x18\v \x01(\v2\x18.social.chat.MessagePushH\x00R\vmessagePush\x12L\n" +
	"\x11conversation_push\x18\f \x01(\v2\x1d.social.chat.ConversationPushH\x00R\x10conversationPushB\t\n" +
	"\apayload*q\n" +
	"\x10ConversationType\x12!\n" +
	"\x1dCONVERSATION_TYPE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19CONVERSATION_TYPE_PRIVATE\x10\x01\x12\x1b\n" +
	"\x17CONVERSATION_TYPE_GROUP\x10\x02*s\n" +
	"\vMessageType\x12\x1c\n" +
	"\x18MESSAGE_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11MESSAGE_TYPE_TEXT\x10\x01\x12\x16\n" +
	"\x12MESSAGE_TYPE_IMAGE\x10\x02\x12\x17\n" +
	"\x13MESSAGE_TYPE_SYSTEM\x10\x03B%Z#social_app/internal/proto/chat;chatb\x06proto3"

var (
	file_chat_chat_proto_rawDescOnce sync.Once
	file_chat_chat_proto_rawDescData []byte
)

func file_chat_chat_proto_rawDescGZIP() []byte {
	file_chat_chat_proto_rawDescOnce.Do(func() {
		file_chat_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chat_chat_proto_rawDesc), len(file_chat_chat_proto_rawDesc)))
	})
	return file_chat_chat_proto_rawDescData
}

var file_chat_chat_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_chat_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_chat_chat_proto_goTypes = []any{
	(ConversationType)(0),               // 0: social.chat.ConversationType
	(MessageType)(0),                    // 1: social.chat.MessageType
	(*Conversation)(nil),                // 2: social.chat.Conversation
	(*SenderInfo)(nil),                  // 3: social.chat.SenderInfo
	(*Message)(nil),                     // 4: social.chat.Message
	(*SendMessageRequest)(nil),          // 5: social.chat.SendMessageRequest
	(*SendMessageResponse)(nil),         // 6: social.chat.SendMessageResponse
	(*GetConversationListRequest)(nil),  // 7: social.chat.GetConversationListRequest
	(*GetConversationListResponse)(nil), // 8: social.chat.GetConversationListResponse
	(*GetMessageListRequest)(nil),       // 9: social.chat.GetMessageListRequest
	(*GetMessageListResponse)(nil),      // 10: social.chat.GetMessageListResponse
	(*MarkAsReadRequest)(nil),           // 11: social.chat.MarkAsReadRequest
	(*MarkAsReadResponse)(nil),          // 12: social.chat.MarkAsReadResponse
	(*CreateConversationRequest)(nil),   // 13: social.chat.CreateConversationRequest
	(*CreateConversationResponse)(nil),  // 14: social.chat.CreateConversationResponse
	(*MessagePush)(nil),                 // 15: social.chat.MessagePush
	(*ConversationPush)(nil),            // 16: social.chat.ConversationPush
	(*ChatPayload)(nil),                 // 17: social.chat.ChatPayload
	(*timestamppb.Timestamp)(nil),       // 18: google.protobuf.Timestamp
}
var file_chat_chat_proto_depIdxs = []int32{
	0,  // 0: social.chat.Conversation.type:type_name -> social.chat.ConversationType
	4,  // 1: social.chat.Conversation.last_message:type_name -> social.chat.Message
	18, // 2: social.chat.Conversation.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 3: social.chat.Message.type:type_name -> social.chat.MessageType
	18, // 4: social.chat.Message.created_at:type_name -> google.protobuf.Timestamp
	3,  // 5: social.chat.Message.sender:type_name -> social.chat.SenderInfo
	1,  // 6: social.chat.SendMessageRequest.type:type_name -> social.chat.MessageType
	4,  // 7: social.chat.SendMessageResponse.message:type_name -> social.chat.Message
	2,  // 8: social.chat.GetConversationListResponse.conversations:type_name -> social.chat.Conversation
	4,  // 9: social.chat.GetMessageListResponse.messages:type_name -> social.chat.Message
	0,  // 10: social.chat.CreateConversationRequest.type:type_name -> social.chat.ConversationType
	2,  // 11: social.chat.CreateConversationResponse.conversation:type_name -> social.chat.Conversation
	4,  // 12: social.chat.MessagePush.message:type_name -> social.chat.Message
	2,  // 13: social.chat.ConversationPush.conversation:type_name -> social.chat.Conversation
	5,  // 14: social.chat.ChatPayload.send_message:type_name -> social.chat.SendMessageRequest
	6,  // 15: social.chat.ChatPayload.send_message_response:type_name -> social.chat.SendMessageResponse
	7,  // 16: social.chat.ChatPayload.get_conversation_list:type_name -> social.chat.GetConversationListRequest
	8,  // 17: social.chat.ChatPayload.get_conversation_list_response:type_name -> social.chat.GetConversationListResponse
	9,  // 18: social.chat.ChatPayload.get_message_list:type_name -> social.chat.GetMessageListRequest
	10, // 19: social.chat.ChatPayload.get_message_list_response:type_name -> social.chat.GetMessageListResponse
	11, // 20: social.chat.ChatPayload.mark_as_read:type_name -> social.chat.MarkAsReadRequest
	12, // 21: social.chat.ChatPayload.mark_as_read_response:type_name -> social.chat.MarkAsReadResponse
	13, // 22: social.chat.ChatPayload.create_conversation:type_name -> social.chat.CreateConversationRequest
	14, // 23: social.chat.ChatPayload.create_conversation_response:type_name -> social.chat.CreateConversationResponse
	15, // 24: social.chat.ChatPayload.message_push:type_name -> social.chat.MessagePush
	16, // 25: social.chat.ChatPayload.conversation_push:type_name -> social.chat.ConversationPush
	26, // [26:26] is the sub-list for method output_type
	26, // [26:26] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_chat_chat_proto_init() }
func file_chat_chat_proto_init() {
	if File_chat_chat_proto != nil {
		return
	}
	file_chat_chat_proto_msgTypes[15].OneofWrappers = []any{
		(*ChatPayload_SendMessage)(nil),
		(*ChatPayload_SendMessageResponse)(nil),
		(*ChatPayload_GetConversationList)(nil),
		(*ChatPayload_GetConversationListResponse)(nil),
		(*ChatPayload_GetMessageList)(nil),
		(*ChatPayload_GetMessageListResponse)(nil),
		(*ChatPayload_MarkAsRead)(nil),
		(*ChatPayload_MarkAsReadResponse)(nil),
		(*ChatPayload_CreateConversation)(nil),
		(*ChatPayload_CreateConversationResponse)(nil),
		(*ChatPayload_MessagePush)(nil),
		(*ChatPayload_ConversationPush)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chat_chat_proto_rawDesc), len(file_chat_chat_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chat_chat_proto_goTypes,
		DependencyIndexes: file_chat_chat_proto_depIdxs,
		EnumInfos:         file_chat_chat_proto_enumTypes,
		MessageInfos:      file_chat_chat_proto_msgTypes,
	}.Build()
	File_chat_chat_proto = out.File
	file_chat_chat_proto_goTypes = nil
	file_chat_chat_proto_depIdxs = nil
}
