// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none"
// @generated from file common/error_code.proto (package social, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file common/error_code.proto.
 */
export const file_common_error_code: GenFile = /*@__PURE__*/
  fileDesc("Chdjb21tb24vZXJyb3JfY29kZS5wcm90bxIGc29jaWFsKqsBCglFcnJvckNvZGUSGgoWRVJST1JfQ09ERV9VTlNQRUNJRklFRBAAEhEKDUVSUk9SX0NPREVfT0sQARIbChdFUlJPUl9DT0RFX1VOQVVUSE9SSVpFRBACEhgKFEVSUk9SX0NPREVfTk9UX0ZPVU5EEAMSHwobRVJST1JfQ09ERV9JTlZBTElEX0FSR1VNRU5UEAQSFwoTRVJST1JfQ09ERV9JTlRFUk5BTBAFQilaJ3NvY2lhbF9hcHAvaW50ZXJuYWwvcHJvdG8vY29tbW9uO2NvbW1vbmIGcHJvdG8z");

/**
 * @generated from enum social.ErrorCode
 */
export enum ErrorCode {
  /**
   * @generated from enum value: ERROR_CODE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: ERROR_CODE_OK = 1;
   */
  OK = 1,

  /**
   * @generated from enum value: ERROR_CODE_UNAUTHORIZED = 2;
   */
  UNAUTHORIZED = 2,

  /**
   * @generated from enum value: ERROR_CODE_NOT_FOUND = 3;
   */
  NOT_FOUND = 3,

  /**
   * @generated from enum value: ERROR_CODE_INVALID_ARGUMENT = 4;
   */
  INVALID_ARGUMENT = 4,

  /**
   * @generated from enum value: ERROR_CODE_INTERNAL = 5;
   */
  INTERNAL = 5,
}

/**
 * Describes the enum social.ErrorCode.
 */
export const ErrorCodeSchema: GenEnum<ErrorCode> = /*@__PURE__*/
  enumDesc(file_common_error_code, 0);

