// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none"
// @generated from file common/file.proto (package social.common, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ErrorCode } from "./error_code_pb";
import { file_common_error_code } from "./error_code_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file common/file.proto.
 */
export const file_common_file: GenFile = /*@__PURE__*/
  fileDesc("ChFjb21tb24vZmlsZS5wcm90bxINc29jaWFsLmNvbW1vbiJZChJVcGxvYWRGaWxlUmVzcG9uc2USJQoKZXJyb3JfY29kZRgBIAEoDjIRLnNvY2lhbC5FcnJvckNvZGUSDwoHbWVzc2FnZRgCIAEoCRILCgN1cmwYAyABKAlCKVonc29jaWFsX2FwcC9pbnRlcm5hbC9wcm90by9jb21tb247Y29tbW9uYgZwcm90bzM", [file_common_error_code]);

/**
 * @generated from message social.common.UploadFileResponse
 */
export type UploadFileResponse = Message<"social.common.UploadFileResponse"> & {
  /**
   * @generated from field: social.ErrorCode error_code = 1;
   */
  errorCode: ErrorCode;

  /**
   * @generated from field: string message = 2;
   */
  message: string;

  /**
   * @generated from field: string url = 3;
   */
  url: string;
};

/**
 * Describes the message social.common.UploadFileResponse.
 * Use `create(UploadFileResponseSchema)` to create a new message.
 */
export const UploadFileResponseSchema: GenMessage<UploadFileResponse> = /*@__PURE__*/
  messageDesc(file_common_file, 0);

