// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: ws.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	account "social_app/internal/proto/account"
	chat "social_app/internal/proto/chat"
	relation "social_app/internal/proto/relation"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WsMessageType int32

const (
	WsMessageType_WS_MESSAGE_TYPE_UNSPECIFIED             WsMessageType = 0
	WsMessageType_WS_TYPE_PING                            WsMessageType = 1
	WsMessageType_WS_TYPE_AUTH                            WsMessageType = 2
	WsMessageType_WS_TYPE_PONG                            WsMessageType = 101
	WsMessageType_WS_TYPE_AUTH_RESPONSE                   WsMessageType = 102
	WsMessageType_WS_TYPE_ERROR                           WsMessageType = 103
	WsMessageType_WS_TYPE_ACCOUNT_SEARCH_USER             WsMessageType = 104
	WsMessageType_WS_TYPE_ACCOUNT_SEARCH_USER_RESPONSE    WsMessageType = 105
	WsMessageType_WS_TYPE_ACCOUNT_UPDATE_PROFILE          WsMessageType = 106
	WsMessageType_WS_TYPE_ACCOUNT_UPDATE_PROFILE_RESPONSE WsMessageType = 107
	WsMessageType_WS_TYPE_ACCOUNT_UPLOAD_AVATAR           WsMessageType = 108
	WsMessageType_WS_TYPE_ACCOUNT_UPLOAD_AVATAR_RESPONSE  WsMessageType = 109
	// Chat Module Types
	WsMessageType_WS_TYPE_CHAT_SEND_MESSAGE            WsMessageType = 201
	WsMessageType_WS_TYPE_CHAT_GET_CONVERSATION_LIST   WsMessageType = 202
	WsMessageType_WS_TYPE_CHAT_GET_MESSAGE_LIST        WsMessageType = 203
	WsMessageType_WS_TYPE_CHAT_MARK_AS_READ            WsMessageType = 204
	WsMessageType_WS_TYPE_CHAT_CREATE_CONVERSATION     WsMessageType = 205
	WsMessageType_WS_TYPE_CHAT_GET_TOPIC_ROOM_LIST     WsMessageType = 206
	WsMessageType_WS_TYPE_CHAT_JOIN_TOPIC_ROOM         WsMessageType = 207
	WsMessageType_WS_TYPE_CHAT_LEAVE_TOPIC_ROOM        WsMessageType = 208
	WsMessageType_WS_TYPE_CHAT_SEND_TOPIC_ROOM_MESSAGE WsMessageType = 209
	WsMessageType_WS_TYPE_CHAT_GET_TOPIC_ROOM_MEMBERS  WsMessageType = 210
	// Chat Module Responses
	WsMessageType_WS_TYPE_CHAT_SEND_MESSAGE_RESPONSE            WsMessageType = 301
	WsMessageType_WS_TYPE_CHAT_GET_CONVERSATION_LIST_RESPONSE   WsMessageType = 302
	WsMessageType_WS_TYPE_CHAT_GET_MESSAGE_LIST_RESPONSE        WsMessageType = 303
	WsMessageType_WS_TYPE_CHAT_MARK_AS_READ_RESPONSE            WsMessageType = 304
	WsMessageType_WS_TYPE_CHAT_CREATE_CONVERSATION_RESPONSE     WsMessageType = 305
	WsMessageType_WS_TYPE_CHAT_GET_TOPIC_ROOM_LIST_RESPONSE     WsMessageType = 306
	WsMessageType_WS_TYPE_CHAT_JOIN_TOPIC_ROOM_RESPONSE         WsMessageType = 307
	WsMessageType_WS_TYPE_CHAT_LEAVE_TOPIC_ROOM_RESPONSE        WsMessageType = 308
	WsMessageType_WS_TYPE_CHAT_SEND_TOPIC_ROOM_MESSAGE_RESPONSE WsMessageType = 309
	WsMessageType_WS_TYPE_CHAT_GET_TOPIC_ROOM_MEMBERS_RESPONSE  WsMessageType = 310
	// Chat Module Push
	WsMessageType_WS_TYPE_CHAT_MESSAGE_PUSH            WsMessageType = 401
	WsMessageType_WS_TYPE_CHAT_CONVERSATION_PUSH       WsMessageType = 402
	WsMessageType_WS_TYPE_CHAT_TOPIC_ROOM_MESSAGE_PUSH WsMessageType = 403
	WsMessageType_WS_TYPE_CHAT_TOPIC_ROOM_MEMBERS_PUSH WsMessageType = 404
	// Relation Module Types (Replaces Contact)
	WsMessageType_WS_TYPE_RELATION_FOLLOW        WsMessageType = 501
	WsMessageType_WS_TYPE_RELATION_UNFOLLOW      WsMessageType = 502
	WsMessageType_WS_TYPE_RELATION_GET_FOLLOWING WsMessageType = 503
	WsMessageType_WS_TYPE_RELATION_GET_FOLLOWERS WsMessageType = 504
	WsMessageType_WS_TYPE_RELATION_GET_FRIENDS   WsMessageType = 505
	WsMessageType_WS_TYPE_RELATION_BLOCK         WsMessageType = 506
	WsMessageType_WS_TYPE_RELATION_UNBLOCK       WsMessageType = 507
	WsMessageType_WS_TYPE_RELATION_GET_BLOCKED   WsMessageType = 508
	// Relation Module Responses
	WsMessageType_WS_TYPE_RELATION_FOLLOW_RESPONSE        WsMessageType = 601
	WsMessageType_WS_TYPE_RELATION_UNFOLLOW_RESPONSE      WsMessageType = 602
	WsMessageType_WS_TYPE_RELATION_GET_FOLLOWING_RESPONSE WsMessageType = 603
	WsMessageType_WS_TYPE_RELATION_GET_FOLLOWERS_RESPONSE WsMessageType = 604
	WsMessageType_WS_TYPE_RELATION_GET_FRIENDS_RESPONSE   WsMessageType = 605
	WsMessageType_WS_TYPE_RELATION_BLOCK_RESPONSE         WsMessageType = 606
	WsMessageType_WS_TYPE_RELATION_UNBLOCK_RESPONSE       WsMessageType = 607
	WsMessageType_WS_TYPE_RELATION_GET_BLOCKED_RESPONSE   WsMessageType = 608
	// Relation Module Push
	WsMessageType_WS_TYPE_RELATION_PUSH WsMessageType = 701
)

// Enum value maps for WsMessageType.
var (
	WsMessageType_name = map[int32]string{
		0:   "WS_MESSAGE_TYPE_UNSPECIFIED",
		1:   "WS_TYPE_PING",
		2:   "WS_TYPE_AUTH",
		101: "WS_TYPE_PONG",
		102: "WS_TYPE_AUTH_RESPONSE",
		103: "WS_TYPE_ERROR",
		104: "WS_TYPE_ACCOUNT_SEARCH_USER",
		105: "WS_TYPE_ACCOUNT_SEARCH_USER_RESPONSE",
		106: "WS_TYPE_ACCOUNT_UPDATE_PROFILE",
		107: "WS_TYPE_ACCOUNT_UPDATE_PROFILE_RESPONSE",
		108: "WS_TYPE_ACCOUNT_UPLOAD_AVATAR",
		109: "WS_TYPE_ACCOUNT_UPLOAD_AVATAR_RESPONSE",
		201: "WS_TYPE_CHAT_SEND_MESSAGE",
		202: "WS_TYPE_CHAT_GET_CONVERSATION_LIST",
		203: "WS_TYPE_CHAT_GET_MESSAGE_LIST",
		204: "WS_TYPE_CHAT_MARK_AS_READ",
		205: "WS_TYPE_CHAT_CREATE_CONVERSATION",
		206: "WS_TYPE_CHAT_GET_TOPIC_ROOM_LIST",
		207: "WS_TYPE_CHAT_JOIN_TOPIC_ROOM",
		208: "WS_TYPE_CHAT_LEAVE_TOPIC_ROOM",
		209: "WS_TYPE_CHAT_SEND_TOPIC_ROOM_MESSAGE",
		210: "WS_TYPE_CHAT_GET_TOPIC_ROOM_MEMBERS",
		301: "WS_TYPE_CHAT_SEND_MESSAGE_RESPONSE",
		302: "WS_TYPE_CHAT_GET_CONVERSATION_LIST_RESPONSE",
		303: "WS_TYPE_CHAT_GET_MESSAGE_LIST_RESPONSE",
		304: "WS_TYPE_CHAT_MARK_AS_READ_RESPONSE",
		305: "WS_TYPE_CHAT_CREATE_CONVERSATION_RESPONSE",
		306: "WS_TYPE_CHAT_GET_TOPIC_ROOM_LIST_RESPONSE",
		307: "WS_TYPE_CHAT_JOIN_TOPIC_ROOM_RESPONSE",
		308: "WS_TYPE_CHAT_LEAVE_TOPIC_ROOM_RESPONSE",
		309: "WS_TYPE_CHAT_SEND_TOPIC_ROOM_MESSAGE_RESPONSE",
		310: "WS_TYPE_CHAT_GET_TOPIC_ROOM_MEMBERS_RESPONSE",
		401: "WS_TYPE_CHAT_MESSAGE_PUSH",
		402: "WS_TYPE_CHAT_CONVERSATION_PUSH",
		403: "WS_TYPE_CHAT_TOPIC_ROOM_MESSAGE_PUSH",
		404: "WS_TYPE_CHAT_TOPIC_ROOM_MEMBERS_PUSH",
		501: "WS_TYPE_RELATION_FOLLOW",
		502: "WS_TYPE_RELATION_UNFOLLOW",
		503: "WS_TYPE_RELATION_GET_FOLLOWING",
		504: "WS_TYPE_RELATION_GET_FOLLOWERS",
		505: "WS_TYPE_RELATION_GET_FRIENDS",
		506: "WS_TYPE_RELATION_BLOCK",
		507: "WS_TYPE_RELATION_UNBLOCK",
		508: "WS_TYPE_RELATION_GET_BLOCKED",
		601: "WS_TYPE_RELATION_FOLLOW_RESPONSE",
		602: "WS_TYPE_RELATION_UNFOLLOW_RESPONSE",
		603: "WS_TYPE_RELATION_GET_FOLLOWING_RESPONSE",
		604: "WS_TYPE_RELATION_GET_FOLLOWERS_RESPONSE",
		605: "WS_TYPE_RELATION_GET_FRIENDS_RESPONSE",
		606: "WS_TYPE_RELATION_BLOCK_RESPONSE",
		607: "WS_TYPE_RELATION_UNBLOCK_RESPONSE",
		608: "WS_TYPE_RELATION_GET_BLOCKED_RESPONSE",
		701: "WS_TYPE_RELATION_PUSH",
	}
	WsMessageType_value = map[string]int32{
		"WS_MESSAGE_TYPE_UNSPECIFIED":                   0,
		"WS_TYPE_PING":                                  1,
		"WS_TYPE_AUTH":                                  2,
		"WS_TYPE_PONG":                                  101,
		"WS_TYPE_AUTH_RESPONSE":                         102,
		"WS_TYPE_ERROR":                                 103,
		"WS_TYPE_ACCOUNT_SEARCH_USER":                   104,
		"WS_TYPE_ACCOUNT_SEARCH_USER_RESPONSE":          105,
		"WS_TYPE_ACCOUNT_UPDATE_PROFILE":                106,
		"WS_TYPE_ACCOUNT_UPDATE_PROFILE_RESPONSE":       107,
		"WS_TYPE_ACCOUNT_UPLOAD_AVATAR":                 108,
		"WS_TYPE_ACCOUNT_UPLOAD_AVATAR_RESPONSE":        109,
		"WS_TYPE_CHAT_SEND_MESSAGE":                     201,
		"WS_TYPE_CHAT_GET_CONVERSATION_LIST":            202,
		"WS_TYPE_CHAT_GET_MESSAGE_LIST":                 203,
		"WS_TYPE_CHAT_MARK_AS_READ":                     204,
		"WS_TYPE_CHAT_CREATE_CONVERSATION":              205,
		"WS_TYPE_CHAT_GET_TOPIC_ROOM_LIST":              206,
		"WS_TYPE_CHAT_JOIN_TOPIC_ROOM":                  207,
		"WS_TYPE_CHAT_LEAVE_TOPIC_ROOM":                 208,
		"WS_TYPE_CHAT_SEND_TOPIC_ROOM_MESSAGE":          209,
		"WS_TYPE_CHAT_GET_TOPIC_ROOM_MEMBERS":           210,
		"WS_TYPE_CHAT_SEND_MESSAGE_RESPONSE":            301,
		"WS_TYPE_CHAT_GET_CONVERSATION_LIST_RESPONSE":   302,
		"WS_TYPE_CHAT_GET_MESSAGE_LIST_RESPONSE":        303,
		"WS_TYPE_CHAT_MARK_AS_READ_RESPONSE":            304,
		"WS_TYPE_CHAT_CREATE_CONVERSATION_RESPONSE":     305,
		"WS_TYPE_CHAT_GET_TOPIC_ROOM_LIST_RESPONSE":     306,
		"WS_TYPE_CHAT_JOIN_TOPIC_ROOM_RESPONSE":         307,
		"WS_TYPE_CHAT_LEAVE_TOPIC_ROOM_RESPONSE":        308,
		"WS_TYPE_CHAT_SEND_TOPIC_ROOM_MESSAGE_RESPONSE": 309,
		"WS_TYPE_CHAT_GET_TOPIC_ROOM_MEMBERS_RESPONSE":  310,
		"WS_TYPE_CHAT_MESSAGE_PUSH":                     401,
		"WS_TYPE_CHAT_CONVERSATION_PUSH":                402,
		"WS_TYPE_CHAT_TOPIC_ROOM_MESSAGE_PUSH":          403,
		"WS_TYPE_CHAT_TOPIC_ROOM_MEMBERS_PUSH":          404,
		"WS_TYPE_RELATION_FOLLOW":                       501,
		"WS_TYPE_RELATION_UNFOLLOW":                     502,
		"WS_TYPE_RELATION_GET_FOLLOWING":                503,
		"WS_TYPE_RELATION_GET_FOLLOWERS":                504,
		"WS_TYPE_RELATION_GET_FRIENDS":                  505,
		"WS_TYPE_RELATION_BLOCK":                        506,
		"WS_TYPE_RELATION_UNBLOCK":                      507,
		"WS_TYPE_RELATION_GET_BLOCKED":                  508,
		"WS_TYPE_RELATION_FOLLOW_RESPONSE":              601,
		"WS_TYPE_RELATION_UNFOLLOW_RESPONSE":            602,
		"WS_TYPE_RELATION_GET_FOLLOWING_RESPONSE":       603,
		"WS_TYPE_RELATION_GET_FOLLOWERS_RESPONSE":       604,
		"WS_TYPE_RELATION_GET_FRIENDS_RESPONSE":         605,
		"WS_TYPE_RELATION_BLOCK_RESPONSE":               606,
		"WS_TYPE_RELATION_UNBLOCK_RESPONSE":             607,
		"WS_TYPE_RELATION_GET_BLOCKED_RESPONSE":         608,
		"WS_TYPE_RELATION_PUSH":                         701,
	}
)

func (x WsMessageType) Enum() *WsMessageType {
	p := new(WsMessageType)
	*p = x
	return p
}

func (x WsMessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WsMessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_ws_proto_enumTypes[0].Descriptor()
}

func (WsMessageType) Type() protoreflect.EnumType {
	return &file_ws_proto_enumTypes[0]
}

func (x WsMessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WsMessageType.Descriptor instead.
func (WsMessageType) EnumDescriptor() ([]byte, []int) {
	return file_ws_proto_rawDescGZIP(), []int{0}
}

type WsError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WsError) Reset() {
	*x = WsError{}
	mi := &file_ws_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WsError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WsError) ProtoMessage() {}

func (x *WsError) ProtoReflect() protoreflect.Message {
	mi := &file_ws_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WsError.ProtoReflect.Descriptor instead.
func (*WsError) Descriptor() ([]byte, []int) {
	return file_ws_proto_rawDescGZIP(), []int{0}
}

func (x *WsError) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *WsError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type WsMessage struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId int64                  `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Type      WsMessageType          `protobuf:"varint,2,opt,name=type,proto3,enum=social.WsMessageType" json:"type,omitempty"`
	Timestamp int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*WsMessage_Account
	//	*WsMessage_Chat
	//	*WsMessage_Relation
	//	*WsMessage_Error
	Payload       isWsMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WsMessage) Reset() {
	*x = WsMessage{}
	mi := &file_ws_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WsMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WsMessage) ProtoMessage() {}

func (x *WsMessage) ProtoReflect() protoreflect.Message {
	mi := &file_ws_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WsMessage.ProtoReflect.Descriptor instead.
func (*WsMessage) Descriptor() ([]byte, []int) {
	return file_ws_proto_rawDescGZIP(), []int{1}
}

func (x *WsMessage) GetRequestId() int64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *WsMessage) GetType() WsMessageType {
	if x != nil {
		return x.Type
	}
	return WsMessageType_WS_MESSAGE_TYPE_UNSPECIFIED
}

func (x *WsMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *WsMessage) GetPayload() isWsMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WsMessage) GetAccount() *account.AccountPayload {
	if x != nil {
		if x, ok := x.Payload.(*WsMessage_Account); ok {
			return x.Account
		}
	}
	return nil
}

func (x *WsMessage) GetChat() *chat.ChatPayload {
	if x != nil {
		if x, ok := x.Payload.(*WsMessage_Chat); ok {
			return x.Chat
		}
	}
	return nil
}

func (x *WsMessage) GetRelation() *relation.RelationPayload {
	if x != nil {
		if x, ok := x.Payload.(*WsMessage_Relation); ok {
			return x.Relation
		}
	}
	return nil
}

func (x *WsMessage) GetError() *WsError {
	if x != nil {
		if x, ok := x.Payload.(*WsMessage_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isWsMessage_Payload interface {
	isWsMessage_Payload()
}

type WsMessage_Account struct {
	Account *account.AccountPayload `protobuf:"bytes,10,opt,name=account,proto3,oneof"`
}

type WsMessage_Chat struct {
	Chat *chat.ChatPayload `protobuf:"bytes,11,opt,name=chat,proto3,oneof"`
}

type WsMessage_Relation struct {
	Relation *relation.RelationPayload `protobuf:"bytes,12,opt,name=relation,proto3,oneof"`
}

type WsMessage_Error struct {
	Error *WsError `protobuf:"bytes,13,opt,name=error,proto3,oneof"`
}

func (*WsMessage_Account) isWsMessage_Payload() {}

func (*WsMessage_Chat) isWsMessage_Payload() {}

func (*WsMessage_Relation) isWsMessage_Payload() {}

func (*WsMessage_Error) isWsMessage_Payload() {}

var File_ws_proto protoreflect.FileDescriptor

const file_ws_proto_rawDesc = "" +
	"\n" +
	"\bws.proto\x12\x06social\x1a\x15account/account.proto\x1a\x0fchat/chat.proto\x1a\x17relation/relation.proto\"7\n" +
	"\aWsError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xd3\x02\n" +
	"\tWsMessage\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x03R\trequestId\x12)\n" +
	"\x04type\x18\x02 \x01(\x0e2\x15.social.WsMessageTypeR\x04type\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12:\n" +
	"\aaccount\x18\n" +
	" \x01(\v2\x1e.social.account.AccountPayloadH\x00R\aaccount\x12.\n" +
	"\x04chat\x18\v \x01(\v2\x18.social.chat.ChatPayloadH\x00R\x04chat\x12>\n" +
	"\brelation\x18\f \x01(\v2 .social.relation.RelationPayloadH\x00R\brelation\x12'\n" +
	"\x05error\x18\r \x01(\v2\x0f.social.WsErrorH\x00R\x05errorB\t\n" +
	"\apayload*\xda\x0f\n" +
	"\rWsMessageType\x12\x1f\n" +
	"\x1bWS_MESSAGE_TYPE_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fWS_TYPE_PING\x10\x01\x12\x10\n" +
	"\fWS_TYPE_AUTH\x10\x02\x12\x10\n" +
	"\fWS_TYPE_PONG\x10e\x12\x19\n" +
	"\x15WS_TYPE_AUTH_RESPONSE\x10f\x12\x11\n" +
	"\rWS_TYPE_ERROR\x10g\x12\x1f\n" +
	"\x1bWS_TYPE_ACCOUNT_SEARCH_USER\x10h\x12(\n" +
	"$WS_TYPE_ACCOUNT_SEARCH_USER_RESPONSE\x10i\x12\"\n" +
	"\x1eWS_TYPE_ACCOUNT_UPDATE_PROFILE\x10j\x12+\n" +
	"'WS_TYPE_ACCOUNT_UPDATE_PROFILE_RESPONSE\x10k\x12!\n" +
	"\x1dWS_TYPE_ACCOUNT_UPLOAD_AVATAR\x10l\x12*\n" +
	"&WS_TYPE_ACCOUNT_UPLOAD_AVATAR_RESPONSE\x10m\x12\x1e\n" +
	"\x19WS_TYPE_CHAT_SEND_MESSAGE\x10\xc9\x01\x12'\n" +
	"\"WS_TYPE_CHAT_GET_CONVERSATION_LIST\x10\xca\x01\x12\"\n" +
	"\x1dWS_TYPE_CHAT_GET_MESSAGE_LIST\x10\xcb\x01\x12\x1e\n" +
	"\x19WS_TYPE_CHAT_MARK_AS_READ\x10\xcc\x01\x12%\n" +
	" WS_TYPE_CHAT_CREATE_CONVERSATION\x10\xcd\x01\x12%\n" +
	" WS_TYPE_CHAT_GET_TOPIC_ROOM_LIST\x10\xce\x01\x12!\n" +
	"\x1cWS_TYPE_CHAT_JOIN_TOPIC_ROOM\x10\xcf\x01\x12\"\n" +
	"\x1dWS_TYPE_CHAT_LEAVE_TOPIC_ROOM\x10\xd0\x01\x12)\n" +
	"$WS_TYPE_CHAT_SEND_TOPIC_ROOM_MESSAGE\x10\xd1\x01\x12(\n" +
	"#WS_TYPE_CHAT_GET_TOPIC_ROOM_MEMBERS\x10\xd2\x01\x12'\n" +
	"\"WS_TYPE_CHAT_SEND_MESSAGE_RESPONSE\x10\xad\x02\x120\n" +
	"+WS_TYPE_CHAT_GET_CONVERSATION_LIST_RESPONSE\x10\xae\x02\x12+\n" +
	"&WS_TYPE_CHAT_GET_MESSAGE_LIST_RESPONSE\x10\xaf\x02\x12'\n" +
	"\"WS_TYPE_CHAT_MARK_AS_READ_RESPONSE\x10\xb0\x02\x12.\n" +
	")WS_TYPE_CHAT_CREATE_CONVERSATION_RESPONSE\x10\xb1\x02\x12.\n" +
	")WS_TYPE_CHAT_GET_TOPIC_ROOM_LIST_RESPONSE\x10\xb2\x02\x12*\n" +
	"%WS_TYPE_CHAT_JOIN_TOPIC_ROOM_RESPONSE\x10\xb3\x02\x12+\n" +
	"&WS_TYPE_CHAT_LEAVE_TOPIC_ROOM_RESPONSE\x10\xb4\x02\x122\n" +
	"-WS_TYPE_CHAT_SEND_TOPIC_ROOM_MESSAGE_RESPONSE\x10\xb5\x02\x121\n" +
	",WS_TYPE_CHAT_GET_TOPIC_ROOM_MEMBERS_RESPONSE\x10\xb6\x02\x12\x1e\n" +
	"\x19WS_TYPE_CHAT_MESSAGE_PUSH\x10\x91\x03\x12#\n" +
	"\x1eWS_TYPE_CHAT_CONVERSATION_PUSH\x10\x92\x03\x12)\n" +
	"$WS_TYPE_CHAT_TOPIC_ROOM_MESSAGE_PUSH\x10\x93\x03\x12)\n" +
	"$WS_TYPE_CHAT_TOPIC_ROOM_MEMBERS_PUSH\x10\x94\x03\x12\x1c\n" +
	"\x17WS_TYPE_RELATION_FOLLOW\x10\xf5\x03\x12\x1e\n" +
	"\x19WS_TYPE_RELATION_UNFOLLOW\x10\xf6\x03\x12#\n" +
	"\x1eWS_TYPE_RELATION_GET_FOLLOWING\x10\xf7\x03\x12#\n" +
	"\x1eWS_TYPE_RELATION_GET_FOLLOWERS\x10\xf8\x03\x12!\n" +
	"\x1cWS_TYPE_RELATION_GET_FRIENDS\x10\xf9\x03\x12\x1b\n" +
	"\x16WS_TYPE_RELATION_BLOCK\x10\xfa\x03\x12\x1d\n" +
	"\x18WS_TYPE_RELATION_UNBLOCK\x10\xfb\x03\x12!\n" +
	"\x1cWS_TYPE_RELATION_GET_BLOCKED\x10\xfc\x03\x12%\n" +
	" WS_TYPE_RELATION_FOLLOW_RESPONSE\x10\xd9\x04\x12'\n" +
	"\"WS_TYPE_RELATION_UNFOLLOW_RESPONSE\x10\xda\x04\x12,\n" +
	"'WS_TYPE_RELATION_GET_FOLLOWING_RESPONSE\x10\xdb\x04\x12,\n" +
	"'WS_TYPE_RELATION_GET_FOLLOWERS_RESPONSE\x10\xdc\x04\x12*\n" +
	"%WS_TYPE_RELATION_GET_FRIENDS_RESPONSE\x10\xdd\x04\x12$\n" +
	"\x1fWS_TYPE_RELATION_BLOCK_RESPONSE\x10\xde\x04\x12&\n" +
	"!WS_TYPE_RELATION_UNBLOCK_RESPONSE\x10\xdf\x04\x12*\n" +
	"%WS_TYPE_RELATION_GET_BLOCKED_RESPONSE\x10\xe0\x04\x12\x1a\n" +
	"\x15WS_TYPE_RELATION_PUSH\x10\xbd\x05B!Z\x1fsocial_app/internal/proto;protob\x06proto3"

var (
	file_ws_proto_rawDescOnce sync.Once
	file_ws_proto_rawDescData []byte
)

func file_ws_proto_rawDescGZIP() []byte {
	file_ws_proto_rawDescOnce.Do(func() {
		file_ws_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ws_proto_rawDesc), len(file_ws_proto_rawDesc)))
	})
	return file_ws_proto_rawDescData
}

var file_ws_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ws_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ws_proto_goTypes = []any{
	(WsMessageType)(0),               // 0: social.WsMessageType
	(*WsError)(nil),                  // 1: social.WsError
	(*WsMessage)(nil),                // 2: social.WsMessage
	(*account.AccountPayload)(nil),   // 3: social.account.AccountPayload
	(*chat.ChatPayload)(nil),         // 4: social.chat.ChatPayload
	(*relation.RelationPayload)(nil), // 5: social.relation.RelationPayload
}
var file_ws_proto_depIdxs = []int32{
	0, // 0: social.WsMessage.type:type_name -> social.WsMessageType
	3, // 1: social.WsMessage.account:type_name -> social.account.AccountPayload
	4, // 2: social.WsMessage.chat:type_name -> social.chat.ChatPayload
	5, // 3: social.WsMessage.relation:type_name -> social.relation.RelationPayload
	1, // 4: social.WsMessage.error:type_name -> social.WsError
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_ws_proto_init() }
func file_ws_proto_init() {
	if File_ws_proto != nil {
		return
	}
	file_ws_proto_msgTypes[1].OneofWrappers = []any{
		(*WsMessage_Account)(nil),
		(*WsMessage_Chat)(nil),
		(*WsMessage_Relation)(nil),
		(*WsMessage_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ws_proto_rawDesc), len(file_ws_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ws_proto_goTypes,
		DependencyIndexes: file_ws_proto_depIdxs,
		EnumInfos:         file_ws_proto_enumTypes,
		MessageInfos:      file_ws_proto_msgTypes,
	}.Build()
	File_ws_proto = out.File
	file_ws_proto_goTypes = nil
	file_ws_proto_depIdxs = nil
}
