// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: relation/relation.proto

package relation

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	account "social_app/internal/proto/account"
	common "social_app/internal/proto/common"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RelationPush_Type int32

const (
	RelationPush_TYPE_UNSPECIFIED RelationPush_Type = 0
	RelationPush_TYPE_FOLLOWED    RelationPush_Type = 1 // Someone followed me
	RelationPush_TYPE_UNFOLLOWED  RelationPush_Type = 2 // Someone unfollowed me (optional, maybe not needed to push)
)

// Enum value maps for RelationPush_Type.
var (
	RelationPush_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_FOLLOWED",
		2: "TYPE_UNFOLLOWED",
	}
	RelationPush_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"TYPE_FOLLOWED":    1,
		"TYPE_UNFOLLOWED":  2,
	}
)

func (x RelationPush_Type) Enum() *RelationPush_Type {
	p := new(RelationPush_Type)
	*p = x
	return p
}

func (x RelationPush_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RelationPush_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_relation_relation_proto_enumTypes[0].Descriptor()
}

func (RelationPush_Type) Type() protoreflect.EnumType {
	return &file_relation_relation_proto_enumTypes[0]
}

func (x RelationPush_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RelationPush_Type.Descriptor instead.
func (RelationPush_Type) EnumDescriptor() ([]byte, []int) {
	return file_relation_relation_proto_rawDescGZIP(), []int{12, 0}
}

// Relation represents a user relationship (following)
type Relation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *account.User          `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`                             // The user I am following (or who follows me)
	CreatedAt     int64                  `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Relation) Reset() {
	*x = Relation{}
	mi := &file_relation_relation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Relation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Relation) ProtoMessage() {}

func (x *Relation) ProtoReflect() protoreflect.Message {
	mi := &file_relation_relation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Relation.ProtoReflect.Descriptor instead.
func (*Relation) Descriptor() ([]byte, []int) {
	return file_relation_relation_proto_rawDescGZIP(), []int{0}
}

func (x *Relation) GetUser() *account.User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *Relation) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// FollowRequest requests to follow a user
type FollowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetUid     uint64                 `protobuf:"varint,1,opt,name=target_uid,json=targetUid,proto3" json:"target_uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowRequest) Reset() {
	*x = FollowRequest{}
	mi := &file_relation_relation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowRequest) ProtoMessage() {}

func (x *FollowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_relation_relation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowRequest.ProtoReflect.Descriptor instead.
func (*FollowRequest) Descriptor() ([]byte, []int) {
	return file_relation_relation_proto_rawDescGZIP(), []int{1}
}

func (x *FollowRequest) GetTargetUid() uint64 {
	if x != nil {
		return x.TargetUid
	}
	return 0
}

type FollowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     common.ErrorCode       `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3,enum=social.ErrorCode" json:"error_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowResponse) Reset() {
	*x = FollowResponse{}
	mi := &file_relation_relation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowResponse) ProtoMessage() {}

func (x *FollowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_relation_relation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowResponse.ProtoReflect.Descriptor instead.
func (*FollowResponse) Descriptor() ([]byte, []int) {
	return file_relation_relation_proto_rawDescGZIP(), []int{2}
}

func (x *FollowResponse) GetErrorCode() common.ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return common.ErrorCode(0)
}

func (x *FollowResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// UnfollowRequest requests to unfollow a user
type UnfollowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetUid     uint64                 `protobuf:"varint,1,opt,name=target_uid,json=targetUid,proto3" json:"target_uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnfollowRequest) Reset() {
	*x = UnfollowRequest{}
	mi := &file_relation_relation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnfollowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfollowRequest) ProtoMessage() {}

func (x *UnfollowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_relation_relation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfollowRequest.ProtoReflect.Descriptor instead.
func (*UnfollowRequest) Descriptor() ([]byte, []int) {
	return file_relation_relation_proto_rawDescGZIP(), []int{3}
}

func (x *UnfollowRequest) GetTargetUid() uint64 {
	if x != nil {
		return x.TargetUid
	}
	return 0
}

type UnfollowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     common.ErrorCode       `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3,enum=social.ErrorCode" json:"error_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnfollowResponse) Reset() {
	*x = UnfollowResponse{}
	mi := &file_relation_relation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnfollowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfollowResponse) ProtoMessage() {}

func (x *UnfollowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_relation_relation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfollowResponse.ProtoReflect.Descriptor instead.
func (*UnfollowResponse) Descriptor() ([]byte, []int) {
	return file_relation_relation_proto_rawDescGZIP(), []int{4}
}

func (x *UnfollowResponse) GetErrorCode() common.ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return common.ErrorCode(0)
}

func (x *UnfollowResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// GetFollowingRequest retrieves the list of users I follow
type GetFollowingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowingRequest) Reset() {
	*x = GetFollowingRequest{}
	mi := &file_relation_relation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowingRequest) ProtoMessage() {}

func (x *GetFollowingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_relation_relation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowingRequest.ProtoReflect.Descriptor instead.
func (*GetFollowingRequest) Descriptor() ([]byte, []int) {
	return file_relation_relation_proto_rawDescGZIP(), []int{5}
}

type GetFollowingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FollowingList []*Relation            `protobuf:"bytes,1,rep,name=following_list,json=followingList,proto3" json:"following_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowingResponse) Reset() {
	*x = GetFollowingResponse{}
	mi := &file_relation_relation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowingResponse) ProtoMessage() {}

func (x *GetFollowingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_relation_relation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowingResponse.ProtoReflect.Descriptor instead.
func (*GetFollowingResponse) Descriptor() ([]byte, []int) {
	return file_relation_relation_proto_rawDescGZIP(), []int{6}
}

func (x *GetFollowingResponse) GetFollowingList() []*Relation {
	if x != nil {
		return x.FollowingList
	}
	return nil
}

// GetFollowersResponse retrieves the list of users following me
type GetFollowersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowersRequest) Reset() {
	*x = GetFollowersRequest{}
	mi := &file_relation_relation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowersRequest) ProtoMessage() {}

func (x *GetFollowersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_relation_relation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowersRequest.ProtoReflect.Descriptor instead.
func (*GetFollowersRequest) Descriptor() ([]byte, []int) {
	return file_relation_relation_proto_rawDescGZIP(), []int{7}
}

type GetFollowersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FollowerList  []*Relation            `protobuf:"bytes,1,rep,name=follower_list,json=followerList,proto3" json:"follower_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowersResponse) Reset() {
	*x = GetFollowersResponse{}
	mi := &file_relation_relation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowersResponse) ProtoMessage() {}

func (x *GetFollowersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_relation_relation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowersResponse.ProtoReflect.Descriptor instead.
func (*GetFollowersResponse) Descriptor() ([]byte, []int) {
	return file_relation_relation_proto_rawDescGZIP(), []int{8}
}

func (x *GetFollowersResponse) GetFollowerList() []*Relation {
	if x != nil {
		return x.FollowerList
	}
	return nil
}

// GetFriendsRequest retrieves the list of mutual friends (bidirectional follow)
type GetFriendsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Cursor        string                 `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"` // e.g., "created_at" of the last item
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFriendsRequest) Reset() {
	*x = GetFriendsRequest{}
	mi := &file_relation_relation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFriendsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFriendsRequest) ProtoMessage() {}

func (x *GetFriendsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_relation_relation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFriendsRequest.ProtoReflect.Descriptor instead.
func (*GetFriendsRequest) Descriptor() ([]byte, []int) {
	return file_relation_relation_proto_rawDescGZIP(), []int{9}
}

func (x *GetFriendsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetFriendsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type GetFriendsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FriendList    []*Relation            `protobuf:"bytes,1,rep,name=friend_list,json=friendList,proto3" json:"friend_list,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFriendsResponse) Reset() {
	*x = GetFriendsResponse{}
	mi := &file_relation_relation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFriendsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFriendsResponse) ProtoMessage() {}

func (x *GetFriendsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_relation_relation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFriendsResponse.ProtoReflect.Descriptor instead.
func (*GetFriendsResponse) Descriptor() ([]byte, []int) {
	return file_relation_relation_proto_rawDescGZIP(), []int{10}
}

func (x *GetFriendsResponse) GetFriendList() []*Relation {
	if x != nil {
		return x.FriendList
	}
	return nil
}

func (x *GetFriendsResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

// RelationPayload wraps all relation related messages
type RelationPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*RelationPayload_Follow
	//	*RelationPayload_FollowResponse
	//	*RelationPayload_Unfollow
	//	*RelationPayload_UnfollowResponse
	//	*RelationPayload_GetFollowing
	//	*RelationPayload_GetFollowingResponse
	//	*RelationPayload_GetFollowers
	//	*RelationPayload_GetFollowersResponse
	//	*RelationPayload_RelationPush
	//	*RelationPayload_GetFriends
	//	*RelationPayload_GetFriendsResponse
	Payload       isRelationPayload_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelationPayload) Reset() {
	*x = RelationPayload{}
	mi := &file_relation_relation_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelationPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationPayload) ProtoMessage() {}

func (x *RelationPayload) ProtoReflect() protoreflect.Message {
	mi := &file_relation_relation_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationPayload.ProtoReflect.Descriptor instead.
func (*RelationPayload) Descriptor() ([]byte, []int) {
	return file_relation_relation_proto_rawDescGZIP(), []int{11}
}

func (x *RelationPayload) GetPayload() isRelationPayload_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RelationPayload) GetFollow() *FollowRequest {
	if x != nil {
		if x, ok := x.Payload.(*RelationPayload_Follow); ok {
			return x.Follow
		}
	}
	return nil
}

func (x *RelationPayload) GetFollowResponse() *FollowResponse {
	if x != nil {
		if x, ok := x.Payload.(*RelationPayload_FollowResponse); ok {
			return x.FollowResponse
		}
	}
	return nil
}

func (x *RelationPayload) GetUnfollow() *UnfollowRequest {
	if x != nil {
		if x, ok := x.Payload.(*RelationPayload_Unfollow); ok {
			return x.Unfollow
		}
	}
	return nil
}

func (x *RelationPayload) GetUnfollowResponse() *UnfollowResponse {
	if x != nil {
		if x, ok := x.Payload.(*RelationPayload_UnfollowResponse); ok {
			return x.UnfollowResponse
		}
	}
	return nil
}

func (x *RelationPayload) GetGetFollowing() *GetFollowingRequest {
	if x != nil {
		if x, ok := x.Payload.(*RelationPayload_GetFollowing); ok {
			return x.GetFollowing
		}
	}
	return nil
}

func (x *RelationPayload) GetGetFollowingResponse() *GetFollowingResponse {
	if x != nil {
		if x, ok := x.Payload.(*RelationPayload_GetFollowingResponse); ok {
			return x.GetFollowingResponse
		}
	}
	return nil
}

func (x *RelationPayload) GetGetFollowers() *GetFollowersRequest {
	if x != nil {
		if x, ok := x.Payload.(*RelationPayload_GetFollowers); ok {
			return x.GetFollowers
		}
	}
	return nil
}

func (x *RelationPayload) GetGetFollowersResponse() *GetFollowersResponse {
	if x != nil {
		if x, ok := x.Payload.(*RelationPayload_GetFollowersResponse); ok {
			return x.GetFollowersResponse
		}
	}
	return nil
}

func (x *RelationPayload) GetRelationPush() *RelationPush {
	if x != nil {
		if x, ok := x.Payload.(*RelationPayload_RelationPush); ok {
			return x.RelationPush
		}
	}
	return nil
}

func (x *RelationPayload) GetGetFriends() *GetFriendsRequest {
	if x != nil {
		if x, ok := x.Payload.(*RelationPayload_GetFriends); ok {
			return x.GetFriends
		}
	}
	return nil
}

func (x *RelationPayload) GetGetFriendsResponse() *GetFriendsResponse {
	if x != nil {
		if x, ok := x.Payload.(*RelationPayload_GetFriendsResponse); ok {
			return x.GetFriendsResponse
		}
	}
	return nil
}

type isRelationPayload_Payload interface {
	isRelationPayload_Payload()
}

type RelationPayload_Follow struct {
	Follow *FollowRequest `protobuf:"bytes,1,opt,name=follow,proto3,oneof"`
}

type RelationPayload_FollowResponse struct {
	FollowResponse *FollowResponse `protobuf:"bytes,2,opt,name=follow_response,json=followResponse,proto3,oneof"`
}

type RelationPayload_Unfollow struct {
	Unfollow *UnfollowRequest `protobuf:"bytes,3,opt,name=unfollow,proto3,oneof"`
}

type RelationPayload_UnfollowResponse struct {
	UnfollowResponse *UnfollowResponse `protobuf:"bytes,4,opt,name=unfollow_response,json=unfollowResponse,proto3,oneof"`
}

type RelationPayload_GetFollowing struct {
	GetFollowing *GetFollowingRequest `protobuf:"bytes,5,opt,name=get_following,json=getFollowing,proto3,oneof"`
}

type RelationPayload_GetFollowingResponse struct {
	GetFollowingResponse *GetFollowingResponse `protobuf:"bytes,6,opt,name=get_following_response,json=getFollowingResponse,proto3,oneof"`
}

type RelationPayload_GetFollowers struct {
	GetFollowers *GetFollowersRequest `protobuf:"bytes,7,opt,name=get_followers,json=getFollowers,proto3,oneof"`
}

type RelationPayload_GetFollowersResponse struct {
	GetFollowersResponse *GetFollowersResponse `protobuf:"bytes,8,opt,name=get_followers_response,json=getFollowersResponse,proto3,oneof"`
}

type RelationPayload_RelationPush struct {
	RelationPush *RelationPush `protobuf:"bytes,9,opt,name=relation_push,json=relationPush,proto3,oneof"`
}

type RelationPayload_GetFriends struct {
	GetFriends *GetFriendsRequest `protobuf:"bytes,10,opt,name=get_friends,json=getFriends,proto3,oneof"`
}

type RelationPayload_GetFriendsResponse struct {
	GetFriendsResponse *GetFriendsResponse `protobuf:"bytes,11,opt,name=get_friends_response,json=getFriendsResponse,proto3,oneof"`
}

func (*RelationPayload_Follow) isRelationPayload_Payload() {}

func (*RelationPayload_FollowResponse) isRelationPayload_Payload() {}

func (*RelationPayload_Unfollow) isRelationPayload_Payload() {}

func (*RelationPayload_UnfollowResponse) isRelationPayload_Payload() {}

func (*RelationPayload_GetFollowing) isRelationPayload_Payload() {}

func (*RelationPayload_GetFollowingResponse) isRelationPayload_Payload() {}

func (*RelationPayload_GetFollowers) isRelationPayload_Payload() {}

func (*RelationPayload_GetFollowersResponse) isRelationPayload_Payload() {}

func (*RelationPayload_RelationPush) isRelationPayload_Payload() {}

func (*RelationPayload_GetFriends) isRelationPayload_Payload() {}

func (*RelationPayload_GetFriendsResponse) isRelationPayload_Payload() {}

type RelationPush struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          RelationPush_Type      `protobuf:"varint,1,opt,name=type,proto3,enum=social.relation.RelationPush_Type" json:"type,omitempty"`
	User          *account.User          `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"` // The user who performed the action
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelationPush) Reset() {
	*x = RelationPush{}
	mi := &file_relation_relation_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelationPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationPush) ProtoMessage() {}

func (x *RelationPush) ProtoReflect() protoreflect.Message {
	mi := &file_relation_relation_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationPush.ProtoReflect.Descriptor instead.
func (*RelationPush) Descriptor() ([]byte, []int) {
	return file_relation_relation_proto_rawDescGZIP(), []int{12}
}

func (x *RelationPush) GetType() RelationPush_Type {
	if x != nil {
		return x.Type
	}
	return RelationPush_TYPE_UNSPECIFIED
}

func (x *RelationPush) GetUser() *account.User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *RelationPush) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_relation_relation_proto protoreflect.FileDescriptor

const file_relation_relation_proto_rawDesc = "" +
	"\n" +
	"\x17relation/relation.proto\x12\x0fsocial.relation\x1a\x17common/error_code.proto\x1a\x15account/account.proto\"S\n" +
	"\bRelation\x12(\n" +
	"\x04user\x18\x01 \x01(\v2\x14.social.account.UserR\x04user\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\x03R\tcreatedAt\".\n" +
	"\rFollowRequest\x12\x1d\n" +
	"\n" +
	"target_uid\x18\x01 \x01(\x04R\ttargetUid\"\\\n" +
	"\x0eFollowResponse\x120\n" +
	"\n" +
	"error_code\x18\x01 \x01(\x0e2\x11.social.ErrorCodeR\terrorCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"0\n" +
	"\x0fUnfollowRequest\x12\x1d\n" +
	"\n" +
	"target_uid\x18\x01 \x01(\x04R\ttargetUid\"^\n" +
	"\x10UnfollowResponse\x120\n" +
	"\n" +
	"error_code\x18\x01 \x01(\x0e2\x11.social.ErrorCodeR\terrorCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x15\n" +
	"\x13GetFollowingRequest\"X\n" +
	"\x14GetFollowingResponse\x12@\n" +
	"\x0efollowing_list\x18\x01 \x03(\v2\x19.social.relation.RelationR\rfollowingList\"\x15\n" +
	"\x13GetFollowersRequest\"V\n" +
	"\x14GetFollowersResponse\x12>\n" +
	"\rfollower_list\x18\x01 \x03(\v2\x19.social.relation.RelationR\ffollowerList\"H\n" +
	"\x11GetFriendsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\"q\n" +
	"\x12GetFriendsResponse\x12:\n" +
	"\vfriend_list\x18\x01 \x03(\v2\x19.social.relation.RelationR\n" +
	"friendList\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\"\xf2\x06\n" +
	"\x0fRelationPayload\x128\n" +
	"\x06follow\x18\x01 \x01(\v2\x1e.social.relation.FollowRequestH\x00R\x06follow\x12J\n" +
	"\x0ffollow_response\x18\x02 \x01(\v2\x1f.social.relation.FollowResponseH\x00R\x0efollowResponse\x12>\n" +
	"\bunfollow\x18\x03 \x01(\v2 .social.relation.UnfollowRequestH\x00R\bunfollow\x12P\n" +
	"\x11unfollow_response\x18\x04 \x01(\v2!.social.relation.UnfollowResponseH\x00R\x10unfollowResponse\x12K\n" +
	"\rget_following\x18\x05 \x01(\v2$.social.relation.GetFollowingRequestH\x00R\fgetFollowing\x12]\n" +
	"\x16get_following_response\x18\x06 \x01(\v2%.social.relation.GetFollowingResponseH\x00R\x14getFollowingResponse\x12K\n" +
	"\rget_followers\x18\a \x01(\v2$.social.relation.GetFollowersRequestH\x00R\fgetFollowers\x12]\n" +
	"\x16get_followers_response\x18\b \x01(\v2%.social.relation.GetFollowersResponseH\x00R\x14getFollowersResponse\x12D\n" +
	"\rrelation_push\x18\t \x01(\v2\x1d.social.relation.RelationPushH\x00R\frelationPush\x12E\n" +
	"\vget_friends\x18\n" +
	" \x01(\v2\".social.relation.GetFriendsRequestH\x00R\n" +
	"getFriends\x12W\n" +
	"\x14get_friends_response\x18\v \x01(\v2#.social.relation.GetFriendsResponseH\x00R\x12getFriendsResponseB\t\n" +
	"\apayload\"\xd4\x01\n" +
	"\fRelationPush\x126\n" +
	"\x04type\x18\x01 \x01(\x0e2\".social.relation.RelationPush.TypeR\x04type\x12(\n" +
	"\x04user\x18\x02 \x01(\v2\x14.social.account.UserR\x04user\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"D\n" +
	"\x04Type\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rTYPE_FOLLOWED\x10\x01\x12\x13\n" +
	"\x0fTYPE_UNFOLLOWED\x10\x02B-Z+social_app/internal/proto/relation;relationb\x06proto3"

var (
	file_relation_relation_proto_rawDescOnce sync.Once
	file_relation_relation_proto_rawDescData []byte
)

func file_relation_relation_proto_rawDescGZIP() []byte {
	file_relation_relation_proto_rawDescOnce.Do(func() {
		file_relation_relation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_relation_relation_proto_rawDesc), len(file_relation_relation_proto_rawDesc)))
	})
	return file_relation_relation_proto_rawDescData
}

var file_relation_relation_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_relation_relation_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_relation_relation_proto_goTypes = []any{
	(RelationPush_Type)(0),       // 0: social.relation.RelationPush.Type
	(*Relation)(nil),             // 1: social.relation.Relation
	(*FollowRequest)(nil),        // 2: social.relation.FollowRequest
	(*FollowResponse)(nil),       // 3: social.relation.FollowResponse
	(*UnfollowRequest)(nil),      // 4: social.relation.UnfollowRequest
	(*UnfollowResponse)(nil),     // 5: social.relation.UnfollowResponse
	(*GetFollowingRequest)(nil),  // 6: social.relation.GetFollowingRequest
	(*GetFollowingResponse)(nil), // 7: social.relation.GetFollowingResponse
	(*GetFollowersRequest)(nil),  // 8: social.relation.GetFollowersRequest
	(*GetFollowersResponse)(nil), // 9: social.relation.GetFollowersResponse
	(*GetFriendsRequest)(nil),    // 10: social.relation.GetFriendsRequest
	(*GetFriendsResponse)(nil),   // 11: social.relation.GetFriendsResponse
	(*RelationPayload)(nil),      // 12: social.relation.RelationPayload
	(*RelationPush)(nil),         // 13: social.relation.RelationPush
	(*account.User)(nil),         // 14: social.account.User
	(common.ErrorCode)(0),        // 15: social.ErrorCode
}
var file_relation_relation_proto_depIdxs = []int32{
	14, // 0: social.relation.Relation.user:type_name -> social.account.User
	15, // 1: social.relation.FollowResponse.error_code:type_name -> social.ErrorCode
	15, // 2: social.relation.UnfollowResponse.error_code:type_name -> social.ErrorCode
	1,  // 3: social.relation.GetFollowingResponse.following_list:type_name -> social.relation.Relation
	1,  // 4: social.relation.GetFollowersResponse.follower_list:type_name -> social.relation.Relation
	1,  // 5: social.relation.GetFriendsResponse.friend_list:type_name -> social.relation.Relation
	2,  // 6: social.relation.RelationPayload.follow:type_name -> social.relation.FollowRequest
	3,  // 7: social.relation.RelationPayload.follow_response:type_name -> social.relation.FollowResponse
	4,  // 8: social.relation.RelationPayload.unfollow:type_name -> social.relation.UnfollowRequest
	5,  // 9: social.relation.RelationPayload.unfollow_response:type_name -> social.relation.UnfollowResponse
	6,  // 10: social.relation.RelationPayload.get_following:type_name -> social.relation.GetFollowingRequest
	7,  // 11: social.relation.RelationPayload.get_following_response:type_name -> social.relation.GetFollowingResponse
	8,  // 12: social.relation.RelationPayload.get_followers:type_name -> social.relation.GetFollowersRequest
	9,  // 13: social.relation.RelationPayload.get_followers_response:type_name -> social.relation.GetFollowersResponse
	13, // 14: social.relation.RelationPayload.relation_push:type_name -> social.relation.RelationPush
	10, // 15: social.relation.RelationPayload.get_friends:type_name -> social.relation.GetFriendsRequest
	11, // 16: social.relation.RelationPayload.get_friends_response:type_name -> social.relation.GetFriendsResponse
	0,  // 17: social.relation.RelationPush.type:type_name -> social.relation.RelationPush.Type
	14, // 18: social.relation.RelationPush.user:type_name -> social.account.User
	19, // [19:19] is the sub-list for method output_type
	19, // [19:19] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_relation_relation_proto_init() }
func file_relation_relation_proto_init() {
	if File_relation_relation_proto != nil {
		return
	}
	file_relation_relation_proto_msgTypes[11].OneofWrappers = []any{
		(*RelationPayload_Follow)(nil),
		(*RelationPayload_FollowResponse)(nil),
		(*RelationPayload_Unfollow)(nil),
		(*RelationPayload_UnfollowResponse)(nil),
		(*RelationPayload_GetFollowing)(nil),
		(*RelationPayload_GetFollowingResponse)(nil),
		(*RelationPayload_GetFollowers)(nil),
		(*RelationPayload_GetFollowersResponse)(nil),
		(*RelationPayload_RelationPush)(nil),
		(*RelationPayload_GetFriends)(nil),
		(*RelationPayload_GetFriendsResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_relation_relation_proto_rawDesc), len(file_relation_relation_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_relation_relation_proto_goTypes,
		DependencyIndexes: file_relation_relation_proto_depIdxs,
		EnumInfos:         file_relation_relation_proto_enumTypes,
		MessageInfos:      file_relation_relation_proto_msgTypes,
	}.Build()
	File_relation_relation_proto = out.File
	file_relation_relation_proto_goTypes = nil
	file_relation_relation_proto_depIdxs = nil
}
