// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: account/account.proto

package account

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	common "social_app/internal/proto/common"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Nickname      string                 `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Bio           string                 `protobuf:"bytes,6,opt,name=bio,proto3" json:"bio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_account_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_account_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_account_account_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *User) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *User) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_account_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_account_account_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     common.ErrorCode       `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3,enum=social.ErrorCode" json:"error_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	User          *User                  `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_account_account_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_account_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_account_account_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterResponse) GetErrorCode() common.ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return common.ErrorCode(0)
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RegisterResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Uid           uint64                 `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_account_account_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_account_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_account_account_proto_rawDescGZIP(), []int{3}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginRequest) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     common.ErrorCode       `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3,enum=social.ErrorCode" json:"error_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	User          *User                  `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_account_account_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_account_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_account_account_proto_rawDescGZIP(), []int{4}
}

func (x *LoginResponse) GetErrorCode() common.ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return common.ErrorCode(0)
}

func (x *LoginResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type AuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Uid           uint64                 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthRequest) Reset() {
	*x = AuthRequest{}
	mi := &file_account_account_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRequest) ProtoMessage() {}

func (x *AuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_account_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRequest.ProtoReflect.Descriptor instead.
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return file_account_account_proto_rawDescGZIP(), []int{5}
}

func (x *AuthRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthRequest) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type AuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     common.ErrorCode       `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3,enum=social.ErrorCode" json:"error_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	User          *User                  `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_account_account_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_account_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_account_account_proto_rawDescGZIP(), []int{6}
}

func (x *AuthResponse) GetErrorCode() common.ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return common.ErrorCode(0)
}

func (x *AuthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AuthResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdateProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nickname      string                 `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,2,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Bio           string                 `protobuf:"bytes,3,opt,name=bio,proto3" json:"bio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_account_account_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_account_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_account_account_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateProfileRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UpdateProfileRequest) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UpdateProfileRequest) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

type UpdateProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     common.ErrorCode       `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3,enum=social.ErrorCode" json:"error_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	User          *User                  `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileResponse) Reset() {
	*x = UpdateProfileResponse{}
	mi := &file_account_account_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileResponse) ProtoMessage() {}

func (x *UpdateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_account_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileResponse.ProtoReflect.Descriptor instead.
func (*UpdateProfileResponse) Descriptor() ([]byte, []int) {
	return file_account_account_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateProfileResponse) GetErrorCode() common.ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return common.ErrorCode(0)
}

func (x *UpdateProfileResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateProfileResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type UploadAvatarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadAvatarRequest) Reset() {
	*x = UploadAvatarRequest{}
	mi := &file_account_account_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadAvatarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadAvatarRequest) ProtoMessage() {}

func (x *UploadAvatarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_account_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadAvatarRequest.ProtoReflect.Descriptor instead.
func (*UploadAvatarRequest) Descriptor() ([]byte, []int) {
	return file_account_account_proto_rawDescGZIP(), []int{9}
}

func (x *UploadAvatarRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *UploadAvatarRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type UploadAvatarResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     common.ErrorCode       `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3,enum=social.ErrorCode" json:"error_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadAvatarResponse) Reset() {
	*x = UploadAvatarResponse{}
	mi := &file_account_account_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadAvatarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadAvatarResponse) ProtoMessage() {}

func (x *UploadAvatarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_account_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadAvatarResponse.ProtoReflect.Descriptor instead.
func (*UploadAvatarResponse) Descriptor() ([]byte, []int) {
	return file_account_account_proto_rawDescGZIP(), []int{10}
}

func (x *UploadAvatarResponse) GetErrorCode() common.ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return common.ErrorCode(0)
}

func (x *UploadAvatarResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UploadAvatarResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_account_account_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_account_account_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_account_account_proto_rawDescGZIP(), []int{11}
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_account_account_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_account_account_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_account_account_proto_rawDescGZIP(), []int{12}
}

type SearchUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUserRequest) Reset() {
	*x = SearchUserRequest{}
	mi := &file_account_account_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUserRequest) ProtoMessage() {}

func (x *SearchUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_account_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUserRequest.ProtoReflect.Descriptor instead.
func (*SearchUserRequest) Descriptor() ([]byte, []int) {
	return file_account_account_proto_rawDescGZIP(), []int{13}
}

func (x *SearchUserRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type SearchUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUserResponse) Reset() {
	*x = SearchUserResponse{}
	mi := &file_account_account_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUserResponse) ProtoMessage() {}

func (x *SearchUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_account_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUserResponse.ProtoReflect.Descriptor instead.
func (*SearchUserResponse) Descriptor() ([]byte, []int) {
	return file_account_account_proto_rawDescGZIP(), []int{14}
}

func (x *SearchUserResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type AccountPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AccountPayload_Ping
	//	*AccountPayload_Pong
	//	*AccountPayload_Auth
	//	*AccountPayload_AuthResponse
	//	*AccountPayload_SearchUser
	//	*AccountPayload_SearchUserResponse
	//	*AccountPayload_UpdateProfile
	//	*AccountPayload_UpdateProfileResponse
	//	*AccountPayload_UploadAvatar
	//	*AccountPayload_UploadAvatarResponse
	Payload       isAccountPayload_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountPayload) Reset() {
	*x = AccountPayload{}
	mi := &file_account_account_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountPayload) ProtoMessage() {}

func (x *AccountPayload) ProtoReflect() protoreflect.Message {
	mi := &file_account_account_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountPayload.ProtoReflect.Descriptor instead.
func (*AccountPayload) Descriptor() ([]byte, []int) {
	return file_account_account_proto_rawDescGZIP(), []int{15}
}

func (x *AccountPayload) GetPayload() isAccountPayload_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AccountPayload) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Payload.(*AccountPayload_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *AccountPayload) GetPong() *Pong {
	if x != nil {
		if x, ok := x.Payload.(*AccountPayload_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

func (x *AccountPayload) GetAuth() *AuthRequest {
	if x != nil {
		if x, ok := x.Payload.(*AccountPayload_Auth); ok {
			return x.Auth
		}
	}
	return nil
}

func (x *AccountPayload) GetAuthResponse() *AuthResponse {
	if x != nil {
		if x, ok := x.Payload.(*AccountPayload_AuthResponse); ok {
			return x.AuthResponse
		}
	}
	return nil
}

func (x *AccountPayload) GetSearchUser() *SearchUserRequest {
	if x != nil {
		if x, ok := x.Payload.(*AccountPayload_SearchUser); ok {
			return x.SearchUser
		}
	}
	return nil
}

func (x *AccountPayload) GetSearchUserResponse() *SearchUserResponse {
	if x != nil {
		if x, ok := x.Payload.(*AccountPayload_SearchUserResponse); ok {
			return x.SearchUserResponse
		}
	}
	return nil
}

func (x *AccountPayload) GetUpdateProfile() *UpdateProfileRequest {
	if x != nil {
		if x, ok := x.Payload.(*AccountPayload_UpdateProfile); ok {
			return x.UpdateProfile
		}
	}
	return nil
}

func (x *AccountPayload) GetUpdateProfileResponse() *UpdateProfileResponse {
	if x != nil {
		if x, ok := x.Payload.(*AccountPayload_UpdateProfileResponse); ok {
			return x.UpdateProfileResponse
		}
	}
	return nil
}

func (x *AccountPayload) GetUploadAvatar() *UploadAvatarRequest {
	if x != nil {
		if x, ok := x.Payload.(*AccountPayload_UploadAvatar); ok {
			return x.UploadAvatar
		}
	}
	return nil
}

func (x *AccountPayload) GetUploadAvatarResponse() *UploadAvatarResponse {
	if x != nil {
		if x, ok := x.Payload.(*AccountPayload_UploadAvatarResponse); ok {
			return x.UploadAvatarResponse
		}
	}
	return nil
}

type isAccountPayload_Payload interface {
	isAccountPayload_Payload()
}

type AccountPayload_Ping struct {
	Ping *Ping `protobuf:"bytes,1,opt,name=ping,proto3,oneof"`
}

type AccountPayload_Pong struct {
	Pong *Pong `protobuf:"bytes,2,opt,name=pong,proto3,oneof"`
}

type AccountPayload_Auth struct {
	Auth *AuthRequest `protobuf:"bytes,3,opt,name=auth,proto3,oneof"`
}

type AccountPayload_AuthResponse struct {
	AuthResponse *AuthResponse `protobuf:"bytes,4,opt,name=auth_response,json=authResponse,proto3,oneof"`
}

type AccountPayload_SearchUser struct {
	SearchUser *SearchUserRequest `protobuf:"bytes,5,opt,name=search_user,json=searchUser,proto3,oneof"`
}

type AccountPayload_SearchUserResponse struct {
	SearchUserResponse *SearchUserResponse `protobuf:"bytes,6,opt,name=search_user_response,json=searchUserResponse,proto3,oneof"`
}

type AccountPayload_UpdateProfile struct {
	UpdateProfile *UpdateProfileRequest `protobuf:"bytes,7,opt,name=update_profile,json=updateProfile,proto3,oneof"`
}

type AccountPayload_UpdateProfileResponse struct {
	UpdateProfileResponse *UpdateProfileResponse `protobuf:"bytes,8,opt,name=update_profile_response,json=updateProfileResponse,proto3,oneof"`
}

type AccountPayload_UploadAvatar struct {
	UploadAvatar *UploadAvatarRequest `protobuf:"bytes,9,opt,name=upload_avatar,json=uploadAvatar,proto3,oneof"`
}

type AccountPayload_UploadAvatarResponse struct {
	UploadAvatarResponse *UploadAvatarResponse `protobuf:"bytes,10,opt,name=upload_avatar_response,json=uploadAvatarResponse,proto3,oneof"`
}

func (*AccountPayload_Ping) isAccountPayload_Payload() {}

func (*AccountPayload_Pong) isAccountPayload_Payload() {}

func (*AccountPayload_Auth) isAccountPayload_Payload() {}

func (*AccountPayload_AuthResponse) isAccountPayload_Payload() {}

func (*AccountPayload_SearchUser) isAccountPayload_Payload() {}

func (*AccountPayload_SearchUserResponse) isAccountPayload_Payload() {}

func (*AccountPayload_UpdateProfile) isAccountPayload_Payload() {}

func (*AccountPayload_UpdateProfileResponse) isAccountPayload_Payload() {}

func (*AccountPayload_UploadAvatar) isAccountPayload_Payload() {}

func (*AccountPayload_UploadAvatarResponse) isAccountPayload_Payload() {}

var File_account_account_proto protoreflect.FileDescriptor

const file_account_account_proto_rawDesc = "" +
	"\n" +
	"\x15account/account.proto\x12\x0esocial.account\x1a\x17common/error_code.proto\"\x8e\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1a\n" +
	"\bnickname\x18\x04 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x05 \x01(\tR\x06avatar\x12\x10\n" +
	"\x03bio\x18\x06 \x01(\tR\x03bio\"_\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"\x9e\x01\n" +
	"\x10RegisterResponse\x120\n" +
	"\n" +
	"error_code\x18\x01 \x01(\x0e2\x11.social.ErrorCodeR\terrorCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12(\n" +
	"\x04user\x18\x04 \x01(\v2\x14.social.account.UserR\x04user\"R\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x10\n" +
	"\x03uid\x18\x03 \x01(\x04R\x03uid\"\x9b\x01\n" +
	"\rLoginResponse\x120\n" +
	"\n" +
	"error_code\x18\x01 \x01(\x0e2\x11.social.ErrorCodeR\terrorCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12(\n" +
	"\x04user\x18\x04 \x01(\v2\x14.social.account.UserR\x04user\"5\n" +
	"\vAuthRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\x04R\x03uid\"\x84\x01\n" +
	"\fAuthResponse\x120\n" +
	"\n" +
	"error_code\x18\x01 \x01(\x0e2\x11.social.ErrorCodeR\terrorCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12(\n" +
	"\x04user\x18\x03 \x01(\v2\x14.social.account.UserR\x04user\"\\\n" +
	"\x14UpdateProfileRequest\x12\x1a\n" +
	"\bnickname\x18\x01 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x02 \x01(\tR\x06avatar\x12\x10\n" +
	"\x03bio\x18\x03 \x01(\tR\x03bio\"\x8d\x01\n" +
	"\x15UpdateProfileResponse\x120\n" +
	"\n" +
	"error_code\x18\x01 \x01(\x0e2\x11.social.ErrorCodeR\terrorCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12(\n" +
	"\x04user\x18\x03 \x01(\v2\x14.social.account.UserR\x04user\"E\n" +
	"\x13UploadAvatarRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"t\n" +
	"\x14UploadAvatarResponse\x120\n" +
	"\n" +
	"error_code\x18\x01 \x01(\x0e2\x11.social.ErrorCodeR\terrorCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\"\x06\n" +
	"\x04Ping\"\x06\n" +
	"\x04Pong\")\n" +
	"\x11SearchUserRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"@\n" +
	"\x12SearchUserResponse\x12*\n" +
	"\x05users\x18\x01 \x03(\v2\x14.social.account.UserR\x05users\"\xe3\x05\n" +
	"\x0eAccountPayload\x12*\n" +
	"\x04ping\x18\x01 \x01(\v2\x14.social.account.PingH\x00R\x04ping\x12*\n" +
	"\x04pong\x18\x02 \x01(\v2\x14.social.account.PongH\x00R\x04pong\x121\n" +
	"\x04auth\x18\x03 \x01(\v2\x1b.social.account.AuthRequestH\x00R\x04auth\x12C\n" +
	"\rauth_response\x18\x04 \x01(\v2\x1c.social.account.AuthResponseH\x00R\fauthResponse\x12D\n" +
	"\vsearch_user\x18\x05 \x01(\v2!.social.account.SearchUserRequestH\x00R\n" +
	"searchUser\x12V\n" +
	"\x14search_user_response\x18\x06 \x01(\v2\".social.account.SearchUserResponseH\x00R\x12searchUserResponse\x12M\n" +
	"\x0eupdate_profile\x18\a \x01(\v2$.social.account.UpdateProfileRequestH\x00R\rupdateProfile\x12_\n" +
	"\x17update_profile_response\x18\b \x01(\v2%.social.account.UpdateProfileResponseH\x00R\x15updateProfileResponse\x12J\n" +
	"\rupload_avatar\x18\t \x01(\v2#.social.account.UploadAvatarRequestH\x00R\fuploadAvatar\x12\\\n" +
	"\x16upload_avatar_response\x18\n" +
	" \x01(\v2$.social.account.UploadAvatarResponseH\x00R\x14uploadAvatarResponseB\t\n" +
	"\apayloadB+Z)social_app/internal/proto/account;accountb\x06proto3"

var (
	file_account_account_proto_rawDescOnce sync.Once
	file_account_account_proto_rawDescData []byte
)

func file_account_account_proto_rawDescGZIP() []byte {
	file_account_account_proto_rawDescOnce.Do(func() {
		file_account_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_account_account_proto_rawDesc), len(file_account_account_proto_rawDesc)))
	})
	return file_account_account_proto_rawDescData
}

var file_account_account_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_account_account_proto_goTypes = []any{
	(*User)(nil),                  // 0: social.account.User
	(*RegisterRequest)(nil),       // 1: social.account.RegisterRequest
	(*RegisterResponse)(nil),      // 2: social.account.RegisterResponse
	(*LoginRequest)(nil),          // 3: social.account.LoginRequest
	(*LoginResponse)(nil),         // 4: social.account.LoginResponse
	(*AuthRequest)(nil),           // 5: social.account.AuthRequest
	(*AuthResponse)(nil),          // 6: social.account.AuthResponse
	(*UpdateProfileRequest)(nil),  // 7: social.account.UpdateProfileRequest
	(*UpdateProfileResponse)(nil), // 8: social.account.UpdateProfileResponse
	(*UploadAvatarRequest)(nil),   // 9: social.account.UploadAvatarRequest
	(*UploadAvatarResponse)(nil),  // 10: social.account.UploadAvatarResponse
	(*Ping)(nil),                  // 11: social.account.Ping
	(*Pong)(nil),                  // 12: social.account.Pong
	(*SearchUserRequest)(nil),     // 13: social.account.SearchUserRequest
	(*SearchUserResponse)(nil),    // 14: social.account.SearchUserResponse
	(*AccountPayload)(nil),        // 15: social.account.AccountPayload
	(common.ErrorCode)(0),         // 16: social.ErrorCode
}
var file_account_account_proto_depIdxs = []int32{
	16, // 0: social.account.RegisterResponse.error_code:type_name -> social.ErrorCode
	0,  // 1: social.account.RegisterResponse.user:type_name -> social.account.User
	16, // 2: social.account.LoginResponse.error_code:type_name -> social.ErrorCode
	0,  // 3: social.account.LoginResponse.user:type_name -> social.account.User
	16, // 4: social.account.AuthResponse.error_code:type_name -> social.ErrorCode
	0,  // 5: social.account.AuthResponse.user:type_name -> social.account.User
	16, // 6: social.account.UpdateProfileResponse.error_code:type_name -> social.ErrorCode
	0,  // 7: social.account.UpdateProfileResponse.user:type_name -> social.account.User
	16, // 8: social.account.UploadAvatarResponse.error_code:type_name -> social.ErrorCode
	0,  // 9: social.account.SearchUserResponse.users:type_name -> social.account.User
	11, // 10: social.account.AccountPayload.ping:type_name -> social.account.Ping
	12, // 11: social.account.AccountPayload.pong:type_name -> social.account.Pong
	5,  // 12: social.account.AccountPayload.auth:type_name -> social.account.AuthRequest
	6,  // 13: social.account.AccountPayload.auth_response:type_name -> social.account.AuthResponse
	13, // 14: social.account.AccountPayload.search_user:type_name -> social.account.SearchUserRequest
	14, // 15: social.account.AccountPayload.search_user_response:type_name -> social.account.SearchUserResponse
	7,  // 16: social.account.AccountPayload.update_profile:type_name -> social.account.UpdateProfileRequest
	8,  // 17: social.account.AccountPayload.update_profile_response:type_name -> social.account.UpdateProfileResponse
	9,  // 18: social.account.AccountPayload.upload_avatar:type_name -> social.account.UploadAvatarRequest
	10, // 19: social.account.AccountPayload.upload_avatar_response:type_name -> social.account.UploadAvatarResponse
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_account_account_proto_init() }
func file_account_account_proto_init() {
	if File_account_account_proto != nil {
		return
	}
	file_account_account_proto_msgTypes[15].OneofWrappers = []any{
		(*AccountPayload_Ping)(nil),
		(*AccountPayload_Pong)(nil),
		(*AccountPayload_Auth)(nil),
		(*AccountPayload_AuthResponse)(nil),
		(*AccountPayload_SearchUser)(nil),
		(*AccountPayload_SearchUserResponse)(nil),
		(*AccountPayload_UpdateProfile)(nil),
		(*AccountPayload_UpdateProfileResponse)(nil),
		(*AccountPayload_UploadAvatar)(nil),
		(*AccountPayload_UploadAvatarResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_account_account_proto_rawDesc), len(file_account_account_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_account_account_proto_goTypes,
		DependencyIndexes: file_account_account_proto_depIdxs,
		MessageInfos:      file_account_account_proto_msgTypes,
	}.Build()
	File_account_account_proto = out.File
	file_account_account_proto_goTypes = nil
	file_account_account_proto_depIdxs = nil
}
