// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: common/error_code.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorCode int32

const (
	ErrorCode_ERROR_CODE_UNSPECIFIED      ErrorCode = 0
	ErrorCode_ERROR_CODE_OK               ErrorCode = 1
	ErrorCode_ERROR_CODE_UNAUTHORIZED     ErrorCode = 2
	ErrorCode_ERROR_CODE_NOT_FOUND        ErrorCode = 3
	ErrorCode_ERROR_CODE_INVALID_ARGUMENT ErrorCode = 4
	ErrorCode_ERROR_CODE_INTERNAL         ErrorCode = 5
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "ERROR_CODE_UNSPECIFIED",
		1: "ERROR_CODE_OK",
		2: "ERROR_CODE_UNAUTHORIZED",
		3: "ERROR_CODE_NOT_FOUND",
		4: "ERROR_CODE_INVALID_ARGUMENT",
		5: "ERROR_CODE_INTERNAL",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNSPECIFIED":      0,
		"ERROR_CODE_OK":               1,
		"ERROR_CODE_UNAUTHORIZED":     2,
		"ERROR_CODE_NOT_FOUND":        3,
		"ERROR_CODE_INVALID_ARGUMENT": 4,
		"ERROR_CODE_INTERNAL":         5,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_common_error_code_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_common_error_code_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_common_error_code_proto_rawDescGZIP(), []int{0}
}

var File_common_error_code_proto protoreflect.FileDescriptor

const file_common_error_code_proto_rawDesc = "" +
	"\n" +
	"\x17common/error_code.proto\x12\x06social*\xab\x01\n" +
	"\tErrorCode\x12\x1a\n" +
	"\x16ERROR_CODE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rERROR_CODE_OK\x10\x01\x12\x1b\n" +
	"\x17ERROR_CODE_UNAUTHORIZED\x10\x02\x12\x18\n" +
	"\x14ERROR_CODE_NOT_FOUND\x10\x03\x12\x1f\n" +
	"\x1bERROR_CODE_INVALID_ARGUMENT\x10\x04\x12\x17\n" +
	"\x13ERROR_CODE_INTERNAL\x10\x05B)Z'social_app/internal/proto/common;commonb\x06proto3"

var (
	file_common_error_code_proto_rawDescOnce sync.Once
	file_common_error_code_proto_rawDescData []byte
)

func file_common_error_code_proto_rawDescGZIP() []byte {
	file_common_error_code_proto_rawDescOnce.Do(func() {
		file_common_error_code_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_error_code_proto_rawDesc), len(file_common_error_code_proto_rawDesc)))
	})
	return file_common_error_code_proto_rawDescData
}

var file_common_error_code_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_error_code_proto_goTypes = []any{
	(ErrorCode)(0), // 0: social.ErrorCode
}
var file_common_error_code_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_error_code_proto_init() }
func file_common_error_code_proto_init() {
	if File_common_error_code_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_error_code_proto_rawDesc), len(file_common_error_code_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_error_code_proto_goTypes,
		DependencyIndexes: file_common_error_code_proto_depIdxs,
		EnumInfos:         file_common_error_code_proto_enumTypes,
	}.Build()
	File_common_error_code_proto = out.File
	file_common_error_code_proto_goTypes = nil
	file_common_error_code_proto_depIdxs = nil
}
