// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: common/file.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     ErrorCode              `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3,enum=social.ErrorCode" json:"error_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileResponse) Reset() {
	*x = UploadFileResponse{}
	mi := &file_common_file_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileResponse) ProtoMessage() {}

func (x *UploadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_file_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileResponse.ProtoReflect.Descriptor instead.
func (*UploadFileResponse) Descriptor() ([]byte, []int) {
	return file_common_file_proto_rawDescGZIP(), []int{0}
}

func (x *UploadFileResponse) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

func (x *UploadFileResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UploadFileResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_common_file_proto protoreflect.FileDescriptor

const file_common_file_proto_rawDesc = "" +
	"\n" +
	"\x11common/file.proto\x12\rsocial.common\x1a\x17common/error_code.proto\"r\n" +
	"\x12UploadFileResponse\x120\n" +
	"\n" +
	"error_code\x18\x01 \x01(\x0e2\x11.social.ErrorCodeR\terrorCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03urlB)Z'social_app/internal/proto/common;commonb\x06proto3"

var (
	file_common_file_proto_rawDescOnce sync.Once
	file_common_file_proto_rawDescData []byte
)

func file_common_file_proto_rawDescGZIP() []byte {
	file_common_file_proto_rawDescOnce.Do(func() {
		file_common_file_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_file_proto_rawDesc), len(file_common_file_proto_rawDesc)))
	})
	return file_common_file_proto_rawDescData
}

var file_common_file_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_common_file_proto_goTypes = []any{
	(*UploadFileResponse)(nil), // 0: social.common.UploadFileResponse
	(ErrorCode)(0),             // 1: social.ErrorCode
}
var file_common_file_proto_depIdxs = []int32{
	1, // 0: social.common.UploadFileResponse.error_code:type_name -> social.ErrorCode
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_common_file_proto_init() }
func file_common_file_proto_init() {
	if File_common_file_proto != nil {
		return
	}
	file_common_error_code_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_file_proto_rawDesc), len(file_common_file_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_file_proto_goTypes,
		DependencyIndexes: file_common_file_proto_depIdxs,
		MessageInfos:      file_common_file_proto_msgTypes,
	}.Build()
	File_common_file_proto = out.File
	file_common_file_proto_goTypes = nil
	file_common_file_proto_depIdxs = nil
}
